from __future__ import annotations

import re
from typing import Any

FIXED_QUESTION_BANK: dict[str, list[str]] = {
    "consistency_frequency": [
        "Ist dir eine Woche, die du sicher schaffst, wichtiger als eine perfekte Woche?",
        "Hilft dir ein einfacher Wochenrhythmus mehr, als jeden Tag neu zu entscheiden?",
        "Wiederholst du lieber gute Standardtage, statt nur selten alles perfekt zu machen?",
        "Hilft dir Planbarkeit meistens mehr als Abwechslung?",
        "Ist für dich meistens besser, wenn die Woche weniger chaotisch ist?",
        "Kommst du mit einem festen Wochenrhythmus gut klar?",
        "Hilft dir eine klar aufgebaute Standardwoche?",
        "Bringt dir Wiederholung eher Fortschritt als Überraschung?",
        "Ist dir eine solide Woche wichtiger als eine extreme Woche?",
        "Ist eine kleine Einheit für dich besser als gar keine Einheit?",
        "Ist ein kurzer, sicherer Trainingstag für dich oft die bessere Lösung?",
        "Trägt ein machbares Minimum deine Woche besser?",
        "Brauchst du eher Rhythmus als Härte?",
        "Funktionieren einfache Standards bei dir am besten?",
        "Hilft dir eine feste Reihenfolge der Tage in der Woche?",
        "Ist Konstanz für dich oft der wichtigste Hebel?",
        "Reagierst du gut auf Wochen, die sich zuverlässig wiederholen?",
        "Gibt dir ein klarer Wochenplan Ruhe?",
        "Fällt dir häufige Einfachheit leichter als seltene Perfektion?",
        "Hilft dir ein vorsichtiger Start in die Woche?",
        "Ist eine verlässliche Trainingshäufigkeit für dich wichtiger als die maximale Qualität jeder einzelnen Einheit?",
        "Bleibst du eher dran, wenn die Einheiten klar und eher klein bleiben?",
        "Hilft dir ein fester Rhythmus für deine Läufe?",
        "Hilft dir ein fester Rhythmus für dein Gym-Training?",
        "Bringt dir eine ruhige Woche mehr als eine volle Woche?",
        "Ist eine stabile Basis für dich oft schon genug?",
        "Reagierst du besser auf Regelmäßigkeit als auf einzelne Spitzen?",
        "Hilft dir nach Pausen ein vorsichtiger Wiedereinstieg?",
        "Brauchst du nach Lücken eher Stabilität?",
        "Ist nach einer Pause ein einfacher Restart für dich am besten?",
        "Hilft dir ein festes Grundgerüst mehr als tägliches Improvisieren?",
        "Bleibst du leichter dran, wenn die Tage klar zugeordnet sind?",
        "Hilft dir ein überschaubarer Umfang dabei, konstant zu bleiben?",
        "Ist eine sichere Woche für dich wertvoller als eine perfekte Woche?",
        "Klappt dein Training besser, wenn es wenig Reibung und Hürden gibt?",
        "Brauchst du möglichst wenig Hürden zwischen Plan und Start?",
        "Hilft dir an schwachen Tagen ein kurzer Pflichtteil?",
        "Ist ein planbarer Standardtag für dich oft schon genug?",
        "Kommst du mit Rhythmus besser klar als mit Chaos?",
        "Hilft dir ein einfaches Minimum, wenn die Woche eng wird?",
        "Ist eine klare Basiswoche für dich stark?",
        "Funktioniert bei dir Wiederholung besser als Improvisation?",
        "Reagierst du gut auf kleine, häufige Reize?",
        "Helfen dir feste Slots im Kalender?",
        "Ist eine ruhige Steigerung für dich besser als ein großer Sprung?",
        "Braucht deine Konstanz eher Klarheit als Motivation?",
        "Gibt dir ein verlässliches Schema Sicherheit?",
        "Ist ein planbarer Ablauf für dich ein echter Vorteil?",
        "Hilft dir ein reduzierter Plan, wenn das Leben voll wird?",
        "Ist Dranbleiben für dich oft wichtiger als Perfektion?",
    ],
    "plan_first": [
        "Wenn der Plan heute Ruhe vorsieht: hältst du dich daran?",
        "Wenn der Tag leicht sein soll: lässt du ihn auch leicht?",
        "Änderst du Einheiten nur, wenn es wirklich einen guten Grund gibt?",
        "Lässt du spontane Extras weg?",
        "Bleibst du bei der geplanten Reihenfolge?",
        "Hältst du dich an den geplanten Umfang?",
        "Verhinderst du, dass ein guter Tag direkt ausartet?",
        "Verhinderst du, dass ein schlechter Tag aus Trotz ausartet?",
        "Folgst du lieber dem Plan als deiner aktuellen Laune?",
        "Wenn das System den Tag vereinfacht: nimmst du diese einfache Lösung an?",
        "Wenn das System dich bremst: gehst du nicht dagegen an?",
        "Machst du Ruhetage wirklich frei?",
        "Lässt du ungeplante Tests weg?",
        "Verschiebst du Einheiten nicht nur, weil du gerade Lust hast?",
        "Wenn heute Z2 geplant ist: bleibt es auch bei Z2?",
        "Wenn heute Technik geplant ist: bleibt es auch bei Technik?",
        "Hältst du dich auch im Urlaub an die Grundstruktur?",
        "Wenn du etwas änderst: ist die Änderung klar begründet?",
        "Bleibst du in einer Deload-Woche wirklich im Deload?",
        "Lässt du zusätzliche Sätze weg, wenn sie nicht geplant sind?",
        "Lässt du spontane Maximalversuche weg?",
        "Hältst du die freien Tage zwischen harten Einheiten ein?",
        "Lässt du das Tempo vom Plan bestimmen?",
        "Wenn das System heute Ernährung priorisiert: bleibst du dabei?",
        "Wenn das System eine Übung bewusst vorsichtiger halten will: akzeptierst du das?",
        "Bleibst du bei einem einfachen Tag einfach?",
        "Hältst du einen lockeren Lauf wirklich locker?",
        "Änderst du nichts nur, weil du gerade motiviert bist?",
        "Änderst du nichts nur, weil du ungeduldig bist?",
        "Folgst du eher der Struktur als deinem Ego?",
        "Wenn der Tag voll ist: kürzt du sauber, statt chaotisch umzubauen?",
        "Hältst du dich an den vorgesehenen Wochenstart?",
        "Bleibst du bei einem gesetzten RPE-Limit?",
        "Wenn das System sagt, heute weniger zu machen: machst du auch weniger?",
        "Wenn das System sagt, heute nur die Basis zu machen: bleibt es bei der Basis?",
        "Hältst du die geplanten Pausen zwischen Lauf und Lower ein?",
        "Verschiebst du Qualitätseinheiten nicht einfach nach Lust?",
        "Bleibst du nach einer starken Einheit trotzdem beim Plan?",
        "Bleibst du nach einer schwachen Einheit trotzdem beim Plan?",
        "Entscheidest du nicht jeden Tag alles komplett neu?",
        "Lässt du die Woche als Ganzes zählen?",
        "Bleibst du bei der vorgesehenen Priorität des Tages?",
        "Wenn das System eine Einheit streicht: lässt du sie auch gestrichen?",
        "Hältst du dich an den Plan, auch wenn du mehr machen könntest?",
        "Hältst du dich an den Plan, auch wenn du wenig Lust hast?",
        "Wenn eine Änderung nötig ist: hältst du sie klein?",
        "Vertraust du dem Plan mehr als dem Impuls des Moments?",
        "Lässt du eine klare Tagesentscheidung stehen?",
        "Wenn das System heute Erholung priorisiert: akzeptierst du das?",
        "Machst du aus einem Ruhetag keinen heimlichen Trainingstag?",
    ],
    "rpe_honesty": [
        "Bist du bei RPE wirklich ehrlich?",
        "Sagst du ehrlich, wenn ein Satz härter war als geplant?",
        "Sagst du ehrlich, wenn ein Satz leichter war als gedacht?",
        "Gibst du zu, wenn du zu nah am Limit warst?",
        "Gibst du zu, wenn noch klar Puffer da war?",
        "Bewertest du den letzten harten Satz ohne Ausreden?",
        "Trennst du Müdigkeit und echtes Limit sauber?",
        "Schreibst du nicht automatisch eine 8, wenn es eher eine 9 war?",
        "Schreibst du nicht automatisch eine 7, wenn es eher eine 6 war?",
        "Kannst du RPE ehrlich eintragen, auch wenn der Log dann schlechter aussieht?",
        "Merkst du ehrlich, wenn du heute eigentlich ein strengeres Limit gebraucht hättest?",
        "Gibst du zu, wenn die Technik zerfallen ist?",
        "Sagst du ehrlich, wenn die letzte Wiederholung grindig war?",
        "Sagst du ehrlich, wenn der Satz sauber war?",
        "Schaffst du es, dein Ego beim Loggen rauszuhalten?",
        "Bewertest du RPE direkt, statt es später schönzureden?",
        "Lässt du gute Stimmung dein RPE nicht verfälschen?",
        "Lässt du Frust dein RPE nicht verfälschen?",
        "Gibst du ehrlich zu, wenn du deine Reserve überschätzt hast?",
        "Gibst du ehrlich zu, wenn du deine Reserve unterschätzt hast?",
        "Redest du eine 9 manchmal kleiner, als sie war?",
        "Machst du eine 7 manchmal härter, als sie war?",
        "Wenn der Satz wacklig war: sagst du das ehrlich?",
        "Wenn der Satz glatt war: sagst du das ehrlich?",
        "Bewertest du RPE über Wochen mit demselben Maßstab?",
        "Bleibst du bei RPE ehrlich, auch wenn der Fortschritt stagniert?",
        "Bleibst du bei RPE ehrlich, auch wenn der Fortschritt gut läuft?",
        "Sagst du ehrlich, wenn die Pausen zu kurz waren?",
        "Sagst du ehrlich, wenn dir die Tagesform geholfen hat?",
        "Sagst du ehrlich, wenn dir die Tagesform geschadet hat?",
        "Erkennst du den Unterschied zwischen hart und hektisch?",
        "Erkennst du den Unterschied zwischen locker und schlampig?",
        "Gibst du zu, wenn du den Satz zu früh aufgegeben hast?",
        "Gibst du zu, wenn du den Satz zu weit getrieben hast?",
        "Bleibt dein RPE bei neuen Übungen genauso ehrlich?",
        "Bleibt dein RPE bei alten Übungen genauso ehrlich?",
        "Bleibst du ehrlich, auch wenn andere Zahlen besser aussehen würden?",
        "Schreibst du nicht das gewünschte RPE, sondern das echte?",
        "Gibst du zu, wenn du es heute nicht gut einschätzen konntest?",
        "Wenn du unsicher bist: bleibst du konservativ und ehrlich?",
        "Sagst du ehrlich, wenn die letzte Wiederholung langsam war?",
        "Sagst du ehrlich, wenn sie sauber und schnell war?",
        "Machst du harte Sätze manchmal kleiner, als sie waren?",
        "Machst du leichte Sätze manchmal größer, als sie waren?",
        "Kannst du RPE ehrlich loggen, ohne dich zu rechtfertigen?",
        "Bleibst du beim gleichen Maßstab wie letzte Woche?",
        "Merkst du, wenn dein Ego die Einschätzung verschiebt?",
        "Merkst du, wenn Müdigkeit die Einschätzung verschiebt?",
        "Würdest du dieselbe Zahl auch morgen noch für richtig halten?",
        "Ist dein RPE eher eine Messung als Wunschdenken?",
    ],
    "logging_quality": [
        "Lässt du bei schlechten Einheiten Details weg?",
        "Rundest du Wiederholungen manchmal nach oben?",
        "Rundest du Gewicht manchmal schöner?",
        "Schreibst du Sätze besser, als sie waren?",
        "Lässt du misslungene Sätze ganz weg?",
        "Loggst du Pausen ungenau?",
        "Loggst du RPE schöner, als es war?",
        "Trägst du später etwas ein, obwohl du es nicht mehr genau weißt?",
        "Änderst du Zahlen rückwirkend, damit es sauberer aussieht?",
        "Lässt du eine schwache Einheit im Log harmloser wirken?",
        "Schreibst du Technikprobleme nicht auf, obwohl sie wichtig waren?",
        "Lässt du Abbrüche weg?",
        "Trägst du nur die guten Sätze ein?",
        "Lässt du bewusst die hässlichen Wiederholungen weg?",
        "Lässt du im Log so wirken, als wäre es ein normaler Tag gewesen, obwohl du eigentlich bewusst reduziert hast?",
        "Schreibst du ein geplantes Ziel statt des echten Ergebnisses auf?",
        "Loggst du nach Gefühl statt nach dem, was wirklich war?",
        "Lässt du einen Satz im Log stehen, obwohl er eigentlich nicht nach deinem normalen Standard war?",
        "Schiebst du das Logging so lange auf, dass Details verloren gehen?",
        "Schreibst du eine runde Zahl, obwohl sie nicht genau war?",
        "Lässt du Fehlversuche weg?",
        "Machst du aus unsauberer Technik im Log einen sauberen Satz?",
        "Loggst du auf Autopilot statt genau?",
        "Überspringst du Notizen, wenn der Tag nicht gut war?",
        "Machst du Probleme kleiner, damit das Log besser aussieht?",
        "Vereinfachst du den Eintrag so stark, dass Wichtiges fehlt?",
        "Trägst du etwas nur ein, damit die Woche sauber aussieht?",
        "Lässt du den Kontext einer schlechten Einheit bewusst weg?",
        "Schreibst du Wiederholungen voll aus, obwohl die letzte nicht sauber war?",
        "Notierst du ein Zielgewicht statt des echten Gewichts?",
        "Lässt du im Log so wirken, als wäre alles nach Plan gelaufen, obwohl du umgestellt hast?",
        "Lässt du eine Pause ungenannt, obwohl sie den Satz verändert hat?",
        "Markierst du eine harte Einheit nicht als hart?",
        "Lässt du niedrige Energie im Log komplett weg?",
        "Änderst du Zahlen, wenn du später Zweifel bekommst?",
        "Schreibst du zu früh aus dem Kopf, statt direkt nach dem Satz?",
        "Machst du aus einem wackligen Satz einen normalen Satz?",
        "Lässt du Trainingsabbrüche lieber unerwähnt?",
        "Schreibst du 'passt schon', obwohl es eigentlich nicht gepasst hat?",
        "Hältst du den Log bewusst knapp, damit Probleme nicht auffallen?",
        "Trägst du Sätze ein, die du nur fast so gemacht hast?",
        "Lässt du Abweichungen vom Plan im Log untergehen?",
        "Schreibst du nur das Ergebnis, aber nicht, wie es gelaufen ist?",
        "Lässt du wichtige Gründe für eine schwache Einheit weg?",
        "Machst du einen unterbrochenen oder neu angesetzten Satz im Log besser, als er war?",
        "Lässt du ein ehrlicheres RPE lieber ganz weg?",
        "Lässt du zusätzliche Müdigkeit weg, obwohl sie die Leistung erklärt?",
        "Loggst du lieber glatt als genau?",
        "Vermeidest du klare Notizen, wenn die Wahrheit nervt?",
        "Wird dein Log manchmal eher schön als ehrlich?",
    ],
    "nutrition_discipline": [
        "Isst du an stressigen Tagen zu wenig?",
        "Vergisst du Mahlzeiten, wenn viel los ist?",
        "Lässt du Protein an chaotischen Tagen schleifen?",
        "Trinkst du zu wenig, wenn der Tag voll ist?",
        "Schiebst du Essen zu lange auf?",
        "Trainierst du hart, obwohl du kaum gegessen hast?",
        "Hoffst du nach schlechtem Essen einfach darauf, es morgen besser zu machen, statt den Tag noch sauber zu retten?",
        "Machst du aus einem Ausrutscher direkt einen ganzen schlechten Tag?",
        "Isst du vor Läufen oft zu unstrukturiert?",
        "Isst du nach harten Einheiten zu spät?",
        "Verlierst du am Wochenende den Überblick?",
        "Baust du stressige Tage ohne klaren Plan um dein Essen herum?",
        "Lässt du Kalorien zu stark schwanken?",
        "Isst du an harten Tagen zu wenig?",
        "Isst du an lockeren Tagen völlig planlos?",
        "Überspringst du vorbereitete Basics, obwohl sie da wären?",
        "Versuchst du schlechte Tage mit Extremreaktionen zu lösen?",
        "Lässt du Hunger zu lange laufen?",
        "Ignorierst du Appetitlosigkeit, statt sie sauber zu lösen?",
        "Isst du auf Reisen deutlich schlechter, als eigentlich nötig wäre?",
        "Lässt du Meal-Prep ausfallen und improvisierst dann nur noch?",
        "Behandelst du Essen so, als wäre es gerade nicht wichtig?",
        "Verlierst du bei Stress als Erstes die Ernährung?",
        "Hältst du Essen absichtlich klein, obwohl das Training läuft?",
        "Isst du unregelmäßig, bis der Tag kippt?",
        "Lässt du Snacks an die Stelle echter Mahlzeiten rutschen?",
        "Isst du nach Müdigkeit eher planlos?",
        "Versuchst du schwache Tage mit Willenskraft statt mit Struktur zu lösen?",
        "Lässt du klare Routinen beim Essen leicht fallen?",
        "Wird Essen bei viel Arbeit schnell zum Nebenthema?",
        "Ignorierst du frühe Hungerzeichen?",
        "Isst du vor wichtigen Sessions manchmal zu wenig?",
        "Isst du nach wichtigen Sessions manchmal zu wenig?",
        "Verpasst du Mahlzeiten, weil du im Flow bist?",
        "Machst du aus Zeitmangel sofort einen schlechten Ess-Tag?",
        "Lässt du einen stressigen Vormittag bis abends alles verschieben?",
        "Isst du zu spät, obwohl der Tag Leistung braucht?",
        "Lässt du eine schlechte Mahlzeit den Rest des Tages entgleisen?",
        "Fällst du bei Müdigkeit eher vom Plan?",
        "Wird dein Essen ungenauer, wenn die Woche hart wird?",
        "Wartest du zu oft, bis du völlig leer bist?",
        "Lässt du einfache Lösungen liegen und improvisierst lieber?",
        "Isst du in harten Phasen weniger verlässlich?",
        "Lässt du Essen zuerst fallen, wenn du Kontrolle verlierst?",
        "Hältst du einen Cut aggressiver durch, als der Plan vorgibt?",
        "Gehst du ohne Plan in lange Tage?",
        "Unterschätzt du oft, wie viel Essen der Tag braucht?",
        "Vermeidest du Klarheit beim Essen, wenn es unbequem wird?",
        "Hoffst du zu oft, dass das Training schlechte Ernährung schon ausgleicht?",
        "Bricht Ernährung bei Stress schneller weg als andere Routinen?",
    ],
    "regeneration_honesty": [
        "Trainierst du nach schlechtem Schlaf trotzdem zu hart?",
        "Verkürzt du Pausen heimlich?",
        "Ignorierst du klare Müdigkeit?",
        "Machst du extra Sätze, obwohl du schon platt bist?",
        "Versuchst du schwache Tage einfach wegzudrücken?",
        "Hältst du einen lockeren Tag nicht locker?",
        "Testest du dich, obwohl der Tag eher nach Bremsen aussieht?",
        "Machst du aus einem ruhigen Tag trotzdem einen vollen Tag?",
        "Schiebst du Erholung zu oft nach hinten?",
        "Gehst du zu spät runter, obwohl dein Körper schon müde ist?",
        "Ignorierst du hohe Müdigkeit, wenn die Motivation da ist?",
        "Versuchst du fehlende Erholung mit Härte zu kompensieren?",
        "Lässt du Warnsignale laufen, bis es knallt?",
        "Nimmst du Erholung erst ernst, wenn gar nichts mehr geht?",
        "Bewegst du dich an Resttagen doch wieder zu viel?",
        "Trainierst du schwer, obwohl du klar merkst, dass es heute nicht passt?",
        "Machst du keine Bremse, obwohl die Technik bricht?",
        "Gibst du schlechten Tagen zu wenig Luft?",
        "Willst du an müden Tagen trotzdem das volle Pensum machen?",
        "Ziehst du Tempo durch, obwohl die Qualität weg ist?",
        "Stellst du Leistung über Erholung, obwohl der Tag kippt?",
        "Ignorierst du schwere Beine im Run?",
        "Ignorierst du Müdigkeit im Gym?",
        "Ziehst du eine Einheit durch, obwohl sie schon früh schlecht aussieht?",
        "Drückst du aus Sturheit weiter?",
        "Schiebst du Schlafprobleme im Training beiseite?",
        "Lässt du Puls und Müdigkeit zu leicht an dir abprallen?",
        "Triffst du harte Entscheidungen lieber gegen als mit deiner Tagesform?",
        "Hältst du an hohen Zielen fest, obwohl der Tag schwach ist?",
        "Nimmst du Signale erst ernst, wenn die Leistung schon weg ist?",
        "Missbrauchst du Motivation als Ersatz für Erholung?",
        "Versuchst du Müdigkeit mit Koffein zu überfahren?",
        "Bleibst du an harten Tagen zu wenig geduldig?",
        "Drückst du Intervalltempo, obwohl die Beine leer sind?",
        "Ziehst du schwere Sätze durch, obwohl dein Rücken schon müde ist?",
        "Nimmst du einen schwachen Start nicht als Warnsignal?",
        "Wird aus 'nur kurz testen' bei dir oft doch eine harte Einheit?",
        "Machst du an müden Tagen zu wenig Anpassungen?",
        "Überspringst du leichte Anpassungen, obwohl sie gereicht hätten?",
        "Nimmst du ein klares Signal zum Bremsen nicht ernst genug?",
        "Bist du an müden Tagen eher zu hart als zu klug?",
        "Bleibst du zu lange in der Einheit, obwohl das Signal klar ist?",
        "Verkürzt du Entlastung, weil du wieder Druck machen willst?",
        "Machst du Lower hart, obwohl die Erholung schon dünn ist?",
        "Läufst du Qualität, obwohl die Vorzeichen schlecht sind?",
        "Gehst du in harte Tage hinein, obwohl du schon leer bist?",
        "Reagierst du auf Müdigkeit oft zu spät?",
        "Übersiehst du kleine Warnzeichen vor harten Einheiten?",
        "Willst du lieber durchziehen als sauber anpassen?",
        "Ist dein erster Impuls bei Müdigkeit eher weiter angreifen als bremsen?",
    ],
    "run_quality": [
        "Machst du Intervalle, obwohl der Tag nicht passt?",
        "Machst du Easy Runs zu schnell?",
        "Läufst du Qualität auf müden Beinen?",
        "Drückst du Pace, obwohl die Form fehlt?",
        "Ignorierst du schwere Beine vor Qualität?",
        "Machst du aus Z2 heimlich Tempo?",
        "Orientierst du dich zu stark an der Uhr?",
        "Jagst du Split-Zahlen, obwohl sich der Lauf nicht gut anfühlt?",
        "Läufst du Qualität nur, weil sie sich im Kopf gut anhört?",
        "Verschiebst du Qualität zu spät?",
        "Ziehst du Intervalltage durch, obwohl die Beine dicht sind?",
        "Machst du einen lockeren Tag unnötig hart?",
        "Versuchst du Läufe mit Willenskraft sauber zu machen?",
        "Läufst du zu schnell an, obwohl Z2 geplant war?",
        "Korrigierst du eine falsche Pace zu spät?",
        "Drückst du gegen schlechte Laufqualität an?",
        "Machst du Tempo, obwohl Erholung fehlt?",
        "Lässt du Lower-Müdigkeit im Lauf zu wenig zählen?",
        "Läufst du Qualität zu nah an schweren Lower-Tagen?",
        "Hältst du an einem harten Run fest, obwohl er kippt?",
        "Wird aus locker bei dir oft moderat?",
        "Wird aus moderat bei dir oft hart?",
        "Wählst du zu oft die heroische statt die saubere Version?",
        "Lässt du beim Laufen öfter dein Ego entscheiden als die Logik?",
        "Machst du aus einem schlechten Start nicht rechtzeitig einen lockeren Tag?",
        "Läufst du weiter auf Pace, obwohl sich der Schritt nicht gut anfühlt?",
        "Ignorierst du schlechte Laufqualität, solange die Uhr okay aussieht?",
        "Versuchst du schlechte Qualität mit noch mehr Druck zu retten?",
        "Tauschst du einen lockeren Run zu schnell gegen Qualität?",
        "Ziehst du Quality Days durch, obwohl die Vorzeichen schlecht sind?",
        "Läufst du zu selten wirklich locker?",
        "Versuchst du Müdigkeit im Lauf wegzudrücken?",
        "Ziehst du Schwellentempo durch, obwohl es heute nicht da ist?",
        "Hältst du dich nicht an den geplanten Reiz?",
        "Machst du eine harte Einheit, obwohl Z2 gereicht hätte?",
        "Läufst du mit müden Hamstrings trotzdem auf Qualität?",
        "Überschätzt du deine Laufbereitschaft?",
        "Verlässt du dich zu wenig auf dein Gefühl, wenn die Uhr etwas anderes sagt?",
        "Schiebst du Erholung im Laufen zu leicht zur Seite?",
        "Machst du aus einem Kontrolltag einen Testtag?",
        "Läufst du eher aus Stolz als aus echter Qualität heraus?",
        "Lässt du einen wackligen Schritt zu lange laufen?",
        "Hältst du an Tempo fest, obwohl die Technik leidet?",
        "Versuchst du einen schlechten Lauf mit Härte zu retten?",
        "Nimmst du ein klares Z2-Signal zu selten an?",
        "Läufst du Qualität eher aus Trotz als aus echter Bereitschaft?",
        "Ist deine Pace öfter zu ambitioniert als sinnvoll?",
        "Wählst du zu oft den schwierigeren statt den klügeren Lauf?",
        "Ignorierst du zu früh, dass heute eigentlich nur locker passt?",
        "Wird aus 'heute nur laufen' bei dir schnell wieder ein Leistungsbeweis?",
    ],
    "regression_response": [
        "Schiebst du Stillstand nur auf Müdigkeit?",
        "Hältst du an einer festgefahrenen Übung zu lange fest?",
        "Drückst du weiter, obwohl seit Wochen nichts vorangeht?",
        "Hoffst du auf den nächsten guten Tag, statt etwas zu ändern?",
        "Redest du dir flache Trends schön?",
        "Ignorierst du wiederholte Warnzeichen bei einer Übung?",
        "Änderst du lieber nichts, obwohl es festhängt?",
        "Hältst du an derselben Lösung fest, obwohl sie nicht greift?",
        "Suchst du Ausreden statt Muster?",
        "Wartest du zu lange auf einen Wendepunkt?",
        "Tust du Plateau-Signale als Zufall ab?",
        "Schiebst du einen echten Rückschritt nur auf die Tagesform?",
        "Hältst du an einem Setup fest, das klar nicht funktioniert?",
        "Tust du dich innerlich schwer damit, den Ansatz zu wechseln?",
        "Versuchst du Stillstand nur mit mehr Druck zu lösen?",
        "Fühlen sich Änderungen für dich eher störend als hilfreich an?",
        "Hoffst du länger als gut ist auf ein 'bald geht es wieder'?",
        "Nimmst du flache Leistung nicht ernst genug?",
        "Lässt du eine schwache Übung einfach mitlaufen?",
        "Vermeidest du klare Entscheidungen bei Stagnation?",
        "Versuchst du Plateaus mit kleinen Ausreden kleinzuhalten?",
        "Bleibst du bei derselben Rep-Range, obwohl nichts passiert?",
        "Bleibst du bei derselben Struktur, obwohl sie nicht greift?",
        "Hältst du am selben Übungsgefühl fest, obwohl Leistung fehlt?",
        "Wartest du länger als nötig auf Fortschritt?",
        "Erklärst du schwache Phasen lieber weg?",
        "Vermeidest du den Gedanken, dass ein Wechsel helfen könnte?",
        "Versuchst du zu viel mit Geduld zu lösen?",
        "Drückst du zu oft einfach weiter?",
        "Wird aus 'noch eine Chance' bei dir schnell ein ganzer Block?",
        "Lässt du stagnierende Übungen zu lange unangetastet?",
        "Hoffst du zu oft, dass sich das Problem von selbst löst?",
        "Blendest du aus, wie lange etwas schon flach läuft?",
        "Hältst du eine schwache Linie zu lange am Leben?",
        "Tust du so, als bräuchte es nur mehr Wille?",
        "Versuchst du Stagnation mit Härte statt mit einem Wechsel zu lösen?",
        "Hängst du an einer Übung, obwohl eine Alternative besser wäre?",
        "Tust du dich schwer mit klaren Schnitten?",
        "Bleibst du eher bei Gewohnheit als bei Wirkung?",
        "Nimmst du ein Plateau erst spät als echtes Signal?",
        "Hältst du einen Ansatz zu lange nur aus Prinzip?",
        "Suchst du zu lange nach dem perfekten Grund für einen Wechsel?",
        "Gibst du schwachen Trends zu lange den Vorteil des Zweifels?",
        "Hoffst du bei Stagnation zu lange auf Zufall?",
        "Hältst du schlechte Serien zu lange für Ausnahmen?",
        "Bleibt oft alles gleich, weil du nichts ändern willst?",
        "Hältst du an alten Ideen fest, obwohl neue besser passen würden?",
        "Versuchst du Rückschritte kleinzureden?",
        "Nimmst du Regression erst ernst, wenn sie deutlich geworden ist?",
        "Bleibst du zu lange beim selben Ansatz, obwohl er leerläuft?",
    ],
}

FIXED_QUESTION_META = {
    "consistency_frequency": {
        "dimension": "frequency_rule",
        "depends": ["gym_frequency", "session_gap", "recovery_state"],
        "pill": "Konstanz × Frequenz",
    },
    "plan_first": {
        "dimension": "discipline",
        "depends": ["recovery_state", "warning_load", "strength_trend"],
        "pill": "Plan zuerst",
    },
    "rpe_honesty": {
        "dimension": "honesty",
        "depends": ["proximity_to_failure", "strength_trend", "warning_load"],
        "pill": "RPE-Ehrlichkeit",
    },
    "logging_quality": {
        "dimension": "honesty",
        "depends": ["strength_trend", "warning_load", "recovery_state"],
        "pill": "Logging",
    },
    "nutrition_discipline": {
        "dimension": "discipline",
        "depends": ["nutrition_adherence", "weight_trend", "recovery_state"],
        "pill": "Essen",
    },
    "regeneration_honesty": {
        "dimension": "recovery",
        "depends": ["recovery_state", "warning_load", "proximity_to_failure"],
        "pill": "Regeneration",
    },
    "run_quality": {
        "dimension": "quality",
        "depends": ["run_load", "recovery_state", "strength_trend"],
        "pill": "Lauf-Qualität",
    },
    "regression_response": {
        "dimension": "response",
        "depends": ["strength_trend", "warning_load", "recovery_state"],
        "pill": "Regression",
    },
}


ADDITIONAL_FIXED_QUESTION_BANK: dict[str, list[str]] = {
    "nutrition_as_limiter": [
        "Soll CORE morgens vor 10:30 Uhr noch nicht wegen zu wenig Tageskalorien bremsen?",
        "Soll CORE offene Makros bis zum Mittag nur als Hinweis sehen und noch nicht als Problem werten?",
        "Wenn das Frühstück gut war, der Rest des Tages aber noch offen ist: soll CORE neutral bleiben?",
        "Soll CORE erst ab dem Nachmittag echten Druck machen, offene Makros aufzuholen?",
        "Wenn eine Mahlzeit ausfällt: soll CORE zuerst die Portionsgröße anderer Meals anpassen, statt direkt ein ganz neues Meal zu ersetzen?",
        "Soll CORE bei einer Proteinlücke zuerst Mengen erhöhen, statt neue Meals zu erzwingen?",
        "Wenn vor einem Lauf Kohlenhydrate fehlen: soll CORE gezielt Carbs priorisieren statt einfach pauschal mehr Kalorien?",
        "Wenn Fett schon hoch ist: soll CORE das Aufholen möglichst fettarm lösen?",
        "Soll CORE bei Abweichungen im Bulk zuerst über das Tagesziel in Kalorien steuern, statt über die Trainingshärte?",
        "Soll CORE bei Abweichungen im Cut zuerst über die Meal-Menge korrigieren, statt über das Meal-Timing?",
        "Wenn Logging lückenhaft ist: soll CORE lieber vorsichtig bleiben, statt aggressiv umzubauen?",
        "Soll CORE bei unsicherem Logging lieber nachfragen, statt still etwas anzuwenden?",
        "Wenn MFP-Import und internes Logging nicht übereinstimmen: soll das interne Logging Vorrang haben?",
        "Soll CORE bei starkem Undereating lieber ein einfaches Notfall-Meal vorschlagen statt ein perfektes Meal zu erzwingen?",
        "Wenn nur noch zwei Zeitfenster übrig sind: darf CORE die Portionen klar erhöhen?",
        "Soll CORE beim Aufholen fehlender Kalorien die Verdauung stärker beachten als nur die nackten Kalorien?",
        "Wenn es abends schon spät ist: soll CORE einen Teil der offenen Makros lieber auf morgen schieben, statt alles noch reinzuquetschen?",
        "Soll CORE bei wiederholtem Auslassen einer Mahlzeit das Standard-Template für diesen Slot vereinfachen?",
        "Wenn Meal-Prep fehlt: soll CORE lieber portable Alternativen wählen, statt Kochen zu erzwingen?",
        "Soll CORE bei niedrigem Protein schon früh am Tag aktiv nach schnellen proteinreichen Optionen fragen?",
        "Wenn die Makros fast im Ziel sind: soll CORE keine kleinen kosmetischen Anpassungen mehr schicken?",
        "Wenn das Tagesziel angepasst wird: soll CORE die Änderung klein halten, zum Beispiel nur um etwa ±150 kcal?",
    ],
    "interference_run_gym": [
        "Wenn heute Lower und morgen ein harter Lauf geplant ist: soll CORE Lower heute vorsichtiger halten?",
        "Wenn heute schon ein harter Lauf war: soll CORE morgen das Gym-Volumen reduzieren?",
        "Wenn der Lauf direkt nach der Schule liegt: soll CORE das Pre-Meal früher und leichter planen?",
        "Wenn zwei harte Reize nah beieinander liegen: soll CORE einen davon bewusst auf eine wiederholbare Version heruntersetzen?",
        "Soll CORE bei einem engen 48-Stunden-Fenster die Gesamtfolge der Einheiten wichtiger nehmen als das Ego des einzelnen Tages?",
        "Wenn die Beine lokal müde sind: soll CORE zuerst die Laufintensität reduzieren?",
        "Wenn die Laufbelastung hoch und die Erholung niedrig ist: soll CORE sowohl den Lauf als auch das Gym zusätzlich absichern?",
        "Wenn ein lockerer Lauf geplant ist, aber das Gym vorher hart war: soll der Lauf strikt locker bleiben?",
        "Soll CORE bei zwei harten Tagen direkt hintereinander automatisch den Schutz vor zu viel Lauf-Gym-Interferenz priorisieren?",
        "Wenn nur eine kurze Session möglich ist: soll CORE die Qualität der Hauptübung wichtiger nehmen als Zusatzvolumen?",
        "Wenn ein Termin mitten am Tag liegt: soll CORE den Reiz zeitlich verschieben statt alles zu verdichten?",
        "Wenn der Schlaf schlecht war und ein Lauf geplant ist: soll CORE aus einer Qualitätseinheit lieber einen lockeren oder längeren Easy-Run machen?",
        "Wenn der Kalender voll ist: soll CORE harte Reize entzerren, statt sie zu stapeln?",
        "Wenn Fußball und Gym kollidieren: soll CORE den Kraftreiz kurz und lokal halten?",
        "Soll CORE bei Interferenz zuerst die Einheit schützen, die morgen schwerer ersetzbar ist?",
        "Wenn ein Run ausfällt: soll CORE das Gym nicht automatisch härter machen?",
        "Wenn das Gym ausfällt: soll CORE den Run nicht automatisch zu einer Qualitätseinheit machen?",
        "Wenn die Wochenlast schon hoch ist: soll CORE zusätzliche Härte trotz guter Tagesform blocken?",
        "Wenn das Zeitfenster knapp ist: soll CORE den Schutz vor Interferenz wichtiger nehmen als die perfekte Planumsetzung?",
        "An Reise- oder Schultagen: soll CORE die Qualität des Reizes wichtiger nehmen als den Umfang?",
    ],
    "signal_weighting": [
        "Soll CORE harte Marker wie HRV oder Ruhepuls höher gewichten als Motivation?",
        "Soll CORE bei widersprüchlichen Signalen eher die vorsichtige Interpretation wählen?",
        "Wenn die Erholung gut aussieht, aber die Leistung fällt: soll die Leistung stärker gewichtet werden?",
        "Wenn die Erholung schlecht ist, aber die Motivation hoch: soll die Erholung Vorrang haben?",
        "Soll CORE niemals ein einzelnes positives Signal über mehrere Warnsignale stellen?",
        "Wenn Daten fehlen: soll CORE eher nah am Plan bleiben, statt zu pushen?",
        "Wenn die Loggingqualität niedrig ist: soll CORE sichtbar machen, dass die Sicherheit der Entscheidung sinkt?",
        "Soll CORE bei Signal-Konflikten klar nennen, welches Signal am Ende den Ausschlag gegeben hat?",
        "Wenn du dich subjektiv top fühlst, die objektiven Daten aber schwach sind: soll CORE die objektiven Daten priorisieren?",
        "Wenn die objektiven Daten neutral sind, du dich aber subjektiv schlecht fühlst: soll CORE moderat schützen statt stark bremsen?",
        "Wenn viele Warnsignale da sind und ein Deload ohnehin bald ansteht: soll CORE frühzeitig auf normalisieren schalten?",
        "Soll CORE in unklaren Situationen lieber kleine, leicht rücknehmbare Entscheidungen treffen?",
        "Wenn der Trend gut ist, aber der Tageswert schlecht: soll CORE den Trend stärker gewichten?",
        "Wenn der Trend schlecht ist, aber der Tageswert gut: soll CORE die Trendwarnung behalten?",
        "Soll CORE bei fehlendem Kontext aus Kalender oder Untis keine aggressiven Timing-Änderungen machen?",
        "Wenn gespeicherte Muster aus CORE-Memory etwas anderes sagen als das aktuelle Tagessignal: soll das Tagessignal Vorrang haben?",
        "Soll CORE ein Thema häufiger abfragen, wenn frühere Vorhersagen dazu wiederholt falsch waren?",
        "Wenn zwei Optionen ähnlich gut sind: soll CORE die wählen, die sich klarer erklären lässt?",
        "Soll CORE bei hoher Unsicherheit lieber fragen statt etwas anzunehmen?",
        "Wenn dein manueller Override wiederholt in dieselbe Richtung geht: soll CORE dieses Muster künftig stärker gewichten?",
    ],
    "deload_philosophy": [
        "Soll CORE einen Deload früher auslösen, wenn sich Warnsignale 2 bis 3 Tage hintereinander häufen?",
        "Wenn nur ein einzelnes Warnsignal da ist: soll CORE noch keinen echten Deload starten?",
        "Soll CORE klar unterscheiden zwischen einem taktisch normalen Tag und einem echten leichten Tag?",
        "Wenn ein Deload aktiv ist: soll CORE trotzdem kleine Qualitätsreize erlauben?",
        "Wenn eine Deload-Woche läuft: soll CORE zuerst das Volumen senken und nicht die Intensität?",
        "Soll CORE die Deload-Entscheidung stärker am Risiko der gesamten Sequenz festmachen als nur am einzelnen Tageswert?",
        "Wenn der Nutzer einen Deload übergeht: soll CORE danach vorsichtiger wieder einsteigen?",
        "Soll CORE vor einem echten Deload erst kleine, leicht rücknehmbare Kürzungen testen?",
        "Wenn Schlaf und Erholung schwach sind: soll die Wahrscheinlichkeit für einen Deload steigen?",
        "Wenn die Leistung trotz Warnsignalen stabil bleibt: soll CORE beim Deload zurückhaltend bleiben?",
        "Soll CORE das Ende eines Deloads erst freigeben, wenn sich mehrere Marker stabilisiert haben?",
        "Wenn ein Deload verkürzt wird: soll CORE beim Wiedereinstieg erst normal statt aggressiv starten?",
        "Soll CORE einen Deload-Hinweis klar als Schutzentscheidung formulieren?",
        "Wenn das Wochenende chaotisch war: soll CORE am Montag eher vorsichtig und deload-nah starten?",
        "Wenn kürzlich Krankheit da war: soll CORE die vorsichtige Deload-Linie länger beibehalten?",
    ],
    "progression_discipline": [
        "Soll CORE Progression nur erlauben, wenn die letzten Ausführungen technisch sauber waren?",
        "Wenn der Trend flach ist: soll CORE lieber kleine Progressionen statt großer Sprünge wählen?",
        "Soll CORE bei unsauberer Technik keine Laststeigerung erlauben?",
        "Wenn die RPE bei den Zielreps zu hoch ist: soll CORE zuerst die Reps stabilisieren?",
        "Wenn die Reps stabil sind, aber das Gewicht stagniert: soll CORE einen kleinen Lastsprung priorisieren?",
        "Wenn eine Übung festhängt: soll CORE lieber die Variante wechseln, statt einfach mehr Druck zu machen?",
        "Soll CORE Progression vorsichtiger setzen, wenn Sessions häufiger ausfallen oder größere Lücken haben?",
        "Wenn die Woche inkonsistent lief: soll CORE die nächste Woche wieder näher an den Plan zurücksetzen?",
        "Wenn die Leistung stark schwankt: soll CORE Stabilität wichtiger nehmen als Rekordjagd?",
        "Soll CORE nach einer Fehlserie eine klare Wiedereinstiegs-Progression vorgeben?",
        "Wenn Overrides mehrfach die Progression stoppen: soll CORE die Sicherheit für weitere Progression senken?",
        "Soll CORE bei Fortschritt immer den kleinsten wirksamen Schritt bevorzugen?",
        "Wenn eine CORE-Aktion nicht umgesetzt wurde: soll die nächste Progressionsstufe verschoben werden?",
        "Wenn das Logging unklar ist: soll CORE Progression pausieren statt raten?",
        "Wenn ein Lift gut läuft, der Gesamtstress aber hoch ist: soll CORE die Progression lokal begrenzen?",
    ],
    "volume_vs_intensity": [
        "Wenn gebremst werden muss: soll CORE zuerst die Satzanzahl reduzieren?",
        "Wenn die Zeit knapp ist: soll CORE die Intensität halten und das Volumen kürzen?",
        "Wenn die Technik bricht: soll CORE eher die Intensität senken als das Volumen?",
        "Wenn die Müdigkeit lokal ist: soll CORE nur die betroffenen Übungen drosseln?",
        "Soll CORE in Push-Phasen zuerst die Intensität anheben und das Volumen stabil lassen?",
        "Wenn die Session kurz wird: soll CORE die Qualität der Hauptsätze wichtiger nehmen als Zusatzsätze?",
        "Wenn die RPE im Verlauf zu hoch driftet: soll CORE das Volumen früh deckeln?",
        "Soll CORE im Deload eher das Volumen als das Gewicht reduzieren?",
        "Wenn Warnsignale moderat sind: soll CORE nur einen Hebel gleichzeitig ändern?",
        "Wenn die Lauf-Interferenz hoch ist: soll CORE zuerst das Lower-Volumen und nicht die Intensität senken?",
        "Wenn die Kalorienlage unklar ist: soll CORE beim Volumen vorsichtiger sein als bei der Intensität?",
        "Soll CORE an zwei Tagen direkt hintereinander das Volumen gleichmäßiger verteilen statt zu bündeln?",
        "Wenn der Nutzer oft abbricht: soll CORE zuerst das Volumen senken statt die Last?",
        "Wenn die Session gut startet, aber hinten kippt: soll CORE die Topsätze behalten und die Backoffs kürzen?",
        "Soll CORE einen Intensitäts-Push nur erlauben, wenn der Rest der Woche noch genug Luft hat?",
    ],
    "proximity_to_failure": [
        "Wenn Topsätze wiederholt zu nah ans Muskelversagen gehen: soll CORE früher ein RPE-Limit setzen?",
        "Soll CORE nach einem Tag mit sehr hoher Nähe zum Limit den nächsten Tag automatisch vorsichtiger gestalten?",
        "Wenn die Satzgeschwindigkeit klar einbricht: soll CORE das auch ohne eingetragenes RPE als hohe Nähe zum Limit werten?",
        "Wenn der Nutzer RPE regelmäßig unterschätzt: soll CORE dann automatisch einen Schutzmechanismus aktivieren?",
        "Soll CORE bei hoher Nähe zum Limit nur den betroffenen Lift schützen statt gleich die ganze Session?",
        "Wenn die Nähe zum Limit niedrig und die Erholung gut ist: darf CORE mehr Druck freigeben?",
        "Wenn die Nähe hoch und die Technik unsauber ist: soll CORE zwei Hebel gleichzeitig ziehen, also Gewicht und Volumen?",
        "Wenn die Nähe hoch war, das Ziel aber erreicht wurde: soll CORE trotzdem kein Extra-Set erlauben?",
        "Soll CORE einen solchen Schutz erst nach mehreren sauberen Sessions wieder lockern?",
        "Wenn Last und Nähe zum Limit beide hoch sind: soll CORE Progression pausieren?",
        "Wenn in mehreren Lifts gleichzeitig hohe Nähe zum Limit auftritt: soll CORE ein globales Schutzsignal setzen?",
        "Wenn dieser Schutz aktiv ist: soll CORE klar erklären, dass Qualität Vorrang hat?",
        "Wenn das Training spät ist und die Müdigkeit hoch: soll CORE die Nähe zum Limit vorsichtiger einschätzen?",
        "Soll CORE bei unvollständigem Set-Logging die Nähe zum Limit eher vorsichtig interpretieren?",
        "Wenn die Nähe zum Limit niedrig ist, aber die Warnlast insgesamt hoch: soll CORE trotzdem nicht pushen?",
    ],
    "calendar_timing_logic": [
        "Wenn die Schule heute früher endet: soll CORE die nächste Mahlzeit aktiv vorziehen?",
        "Wenn zwei Freistunden hintereinander entstehen: soll CORE dieses Fenster für die Hauptmahlzeit nutzen?",
        "Wenn ein Termin mitten in einen Meal-Slot fällt: soll CORE davor statt danach planen?",
        "Wenn der Schultag ungewöhnlich lang ist: soll CORE portable Meals priorisieren?",
        "Wenn der Rückweg länger dauert als geplant: soll CORE Reminder und Timing nach hinten schieben?",
        "Wenn Training direkt nach der Schule liegt: soll CORE das Pre-Meal früher und leichter setzen?",
        "Wenn der Kalender spontan frei wird: soll CORE das Timing aktiv neu ordnen statt starr zu bleiben?",
        "Wenn Unterricht ausfällt: soll CORE den freien Slot zum Aufholen nutzen?",
        "Wenn mehrere Termine dicht beieinander liegen: soll CORE die Form der Mahlzeiten vereinfachen statt am perfekten Meal festzuhalten?",
        "Wenn eine späte Heimkehr ansteht: soll CORE den Aufwand fürs Abendessen automatisch reduzieren?",
        "Wenn nur kurze Pausenfenster bleiben: soll CORE flüssige oder schnelle Optionen bevorzugen?",
        "Wenn der Tagesplan mehrfach springt: soll CORE nur eine stabile Neuplanung schicken statt mehrere kleine Anpassungen?",
        "Wenn Untis und Google-Kalender sich widersprechen: soll CORE den Eintrag nutzen, der zuletzt aktualisiert wurde?",
        "Wenn ein Termin früher endet als gedacht: soll CORE den nächsten Reminder automatisch vorziehen?",
        "Wenn abends Fußball ist: soll CORE Kohlenhydrate eher vor und nach dem Training einplanen statt schon am Vormittag?",
    ],
    "telegram_ops_discipline": [
        "Soll CORE Änderungen beim Timing per Telegram nur einmal nachfragen und den Vorschlag sonst verwerfen?",
        "Wenn auf Telegram kein 'ok' kommt: soll der Vorschlag ohne weitere Nachfrage verfallen?",
        "Soll CORE identische Telegram-Vorschläge zusammenfassen statt sie mehrfach zu senden?",
        "Wenn eine Mahlzeit schon geloggt ist: soll Telegram dafür keine Reminder mehr schicken?",
        "Soll CORE im Telegram-Text den Inhalt der Mahlzeit nennen statt nur die Slot-Nummer?",
        "Wenn ein Kontext aktiv ist: soll 'done' ohne Rückfrage direkt dieser Mahlzeit zugeordnet werden?",
        "Wenn eine Antwort unklar ist: soll Telegram nur eine kurze Rückfrage schicken?",
        "Soll CORE bei eindeutig verständlichen Änderungen auf Telegram auf Rückfragen verzichten?",
        "Wenn ein Vorschlag automatisch verworfen wurde: soll CORE denselben Vorschlag am selben Tag nicht noch einmal senden?",
        "Soll CORE bei 'skip' direkt einen Hinweis zum Aufholen schicken statt noch einmal nach einer Verschiebung zu fragen?",
        "Wenn der User manuell eine Uhrzeit nennt: soll Telegram genau diese Zeit fürs Logging übernehmen?",
        "Soll CORE auf 'ok' oder 'nein' nur minimal reagieren und keinen zusätzlichen Coaching-Text schicken?",
        "Wenn mehrere Meals offen sind: soll Telegram zuerst den wahrscheinlich passenden Slot vorschlagen?",
        "Soll CORE bei Remindern nur dann Antwortoptionen zeigen, wenn dadurch wirklich noch etwas verändert werden kann?",
        "Wenn die Form einer Mahlzeit geändert wurde: soll Telegram kurz die neuen Makros dazu nennen?",
    ],
    "inventory_prep_shopping": [
        "Wenn eine Hauptzutat fehlt: soll CORE direkt eine alternative Meal-Variante wählen?",
        "Soll CORE fehlende Zutaten als Bestandsproblem speichern statt sie nur im Text zu erwähnen?",
        "Wenn der Vorrat knapp wird: soll CORE früh einen Einkaufshinweis für morgen geben?",
        "Wenn ein Meal ohne eine Zutat keinen Sinn mehr ergibt: soll CORE ein Ersatzmeal statt ein halbes Meal vorschlagen?",
        "Soll CORE wiederholt fehlende Zutaten als Prep-Risiko markieren?",
        "Wenn eine portable Option fehlt: soll CORE eine schnell beschaffbare Minimalvariante vorschlagen?",
        "Soll CORE bei einer Lücke am nächsten Morgen schon am Abend vorher einen Prep-Hinweis senden?",
        "Wenn mehrere Meals dieselbe fehlende Zutat brauchen: soll CORE einen gemeinsamen Einkaufshinweis schicken?",
        "Soll CORE bei Bestandsproblemen zuerst einfache Standardfoods priorisieren?",
        "Wenn der tatsächliche Kühlschrankinhalt vom Plan abweicht: soll CORE den Plan pragmatisch an den Bestand anpassen?",
        "Soll CORE bei knapper Zeit Zutaten mit langer Kochzeit meiden?",
        "Wenn eine Proteinquelle leer ist: soll CORE vorübergehend mit schnell verfügbaren Alternativen überbrücken?",
        "Soll CORE Bestandsprobleme im Explain als eigenen Grundcode anzeigen?",
        "Wenn ein Einkaufshinweis ignoriert wurde: soll CORE für die nächsten Tage vorsichtiger planen?",
        "Soll CORE Prep-Empfehlungen nur schicken, wenn sie wirklich einen Nutzen für den nächsten Tag haben?",
    ],
    "explainability_governance": [
        "Soll jede CORE-Änderung einen klaren Reason-Code und zusätzlich einen verständlichen Klartextsatz bekommen?",
        "Soll CORE bei mehreren Gründen immer zuerst den wichtigsten Auslöser nennen?",
        "Wenn die Unsicherheit hoch ist: soll CORE das in der Erklärung ausdrücklich sagen?",
        "Soll CORE klar unterscheiden zwischen 'automatisch angewendet' und 'nur vorgeschlagen, wartet auf ok'?",
        "Wenn der Nutzer manuell eingreift: soll CORE das sichtbar als manual_override festhalten?",
        "Soll CORE rückwirkend zeigen, welche Datenquellen in die Entscheidung eingeflossen sind?",
        "Wenn Daten fehlen: soll CORE das offen benennen statt Sicherheit vorzutäuschen?",
        "Soll CORE ohne 'ok' nur solche Aktionen automatisch anwenden, die leicht rückgängig zu machen sind?",
        "Wenn eine Aktion verworfen wurde: soll CORE den Grund dafür im Trace speichern?",
        "Soll CORE Erklärungen kurz halten, aber immer Ursache und Wirkung nennen?",
        "Wenn mehrere Meal-Änderungen an einem Tag passieren: soll CORE sie zeitlich sortiert gruppieren?",
        "Soll CORE bei jeder Verschiebung die alte und die neue Uhrzeit direkt nebeneinander zeigen?",
        "Wenn das Tagesziel geändert wurde: soll CORE die genaue Änderung in Kalorien nennen, also zum Beispiel +150 oder -150 kcal?",
        "Soll CORE in UI und Telegram dieselbe Sprache für Erklärungen verwenden?",
        "Wenn Regeln miteinander in Konflikt geraten: soll CORE die Prioritätsregel ausdrücklich nennen?",
    ],
    "macro_scaling_control": [
        "Wenn Protein deutlich hinterherhängt: soll CORE zuerst Mengen erhöhen statt ein neues Meal zu bauen?",
        "Soll CORE bei einer Carb-Lücke zuerst die Carb-Komponente der nächsten Mahlzeit erhöhen?",
        "Wenn Fett schon hoch ist: soll CORE das Aufholen möglichst fettarm lösen?",
        "Soll CORE Mengenänderungen pro Meal begrenzen, damit sie realistisch bleiben?",
        "Wenn zwei Meals noch offen sind: soll CORE die Lücke auf beide verteilen statt ein einziges riesiges Meal zu machen?",
        "Soll CORE an einem späten Tag lieber moderat erhöhen und zusätzlich ein kleines Catch-up nutzen?",
        "Wenn nur Porridge betroffen ist: darf CORE die Mengen dort direkt auch ohne Telegram-OK anpassen?",
        "Soll CORE bei allen anderen Meals Mengenänderungen erst nach Telegram-OK übernehmen?",
        "Wenn die Makrolücke klein ist: soll CORE keine Mini-Änderungen unterhalb eines Schwellwerts schicken?",
        "Soll CORE Mengenänderungen in der Erklärung immer als Faktor zeigen, zum Beispiel 1.0x auf 1.25x?",
        "Wenn ein Meal vorher geskipped wurde: soll CORE die nächste Mahlzeit als Catch-up skalieren statt nur zeitlich zu verschieben?",
        "Soll CORE bei starkem Kalorienrückstand zuerst leicht verdauliche Mengen erhöhen?",
        "Wenn das Training bald startet: soll CORE nur solche Bestandteile erhöhen, die als Pre-Meal taugen?",
        "Soll CORE weniger aggressiv skalieren, wenn frühere Vorschläge dieser Art oft abgelehnt wurden?",
        "Wenn der User 'größer' oder 'kleiner' schreibt: soll CORE dafür dieselbe interne Skalierungslogik benutzen wie sonst auch?",
    ],
    "data_freshness_integrity": [
        "Soll CORE Entscheidungen auf Basis veralteter Kalenderdaten ausdrücklich als 'low confidence' markieren?",
        "Wenn Logging nachgetragen wird: soll CORE frühere MISSING-Flags rückwirkend korrigieren?",
        "Soll CORE vergangene Tage nur anhand der final geloggten Daten bewerten und nicht anhand eines alten Live-Status?",
        "Wenn der heutige Tag noch läuft: soll CORE aus frühen Makros noch keine harte Tagesbewertung ableiten?",
        "Soll CORE den laufenden Tag im Energy-Graph ausblenden, bis er abgeschlossen ist?",
        "Wenn Training nachträglich eingetragen wird: soll CORE die Statuskarte sofort neu berechnen?",
        "Wenn ein Run nachgetragen wird: soll CORE dieselbe Rückkorrektur machen wie bei nachgetragenem Training?",
        "Soll CORE Datenquellen mit Zeitstempel priorisieren statt starre Werte?",
        "Wenn Werte als String hereinkommen: soll CORE sie robust umwandeln, statt still daran zu scheitern?",
        "Soll CORE fehlerhafte Inputs sauber abfangen und kontrolliert degradieren statt in einer Dauerschleife zu landen?",
        "Wenn ein Scheduler-Tick keine Änderungen bringt: soll CORE ruhig bleiben und nichts spammen?",
        "Wenn Tagesdaten sich widersprechen: soll CORE den stabileren historischen Wert bevorzugen?",
        "Wenn eine vorgeschlagene Uhrzeit schon vorbei ist: soll CORE auf 'jetzt' oder eine zukünftige Zeit verschieben statt auf die Vergangenheit?",
        "Soll CORE abgelaufene Vorschläge automatisch schließen statt weiter daran zu erinnern?",
        "Wenn eine Aktion schon erledigt ist: soll CORE denselben Schritt danach strikt ignorieren?",
    ],
}

ADDITIONAL_FIXED_QUESTION_META: dict[str, dict[str, Any]] = {
    "nutrition_as_limiter": {
        "dimension": "nutrition_trigger",
        "depends": ["nutrition_adherence", "weight_trend", "recovery_state"],
        "pill": "Ernährung × Limiter",
    },
    "interference_run_gym": {
        "dimension": "interference_horizon",
        "depends": ["run_load", "run_consistency", "recovery_state"],
        "pill": "Lauf × Kraft",
    },
    "signal_weighting": {
        "dimension": "signal_priority",
        "depends": ["recovery_state", "strength_trend", "warning_load"],
        "pill": "Signale × Gewichtung",
    },
    "deload_philosophy": {
        "dimension": "deload_threshold",
        "depends": ["warning_load", "recovery_state", "strength_trend"],
        "pill": "Entlastung × Timing",
    },
    "progression_discipline": {
        "dimension": "progression_rule",
        "depends": ["strength_trend", "proximity_to_failure", "recovery_state"],
        "pill": "Progression × Disziplin",
    },
    "volume_vs_intensity": {
        "dimension": "volume_knob",
        "depends": ["strength_trend", "warning_load", "recovery_state"],
        "pill": "Volumen × Intensität",
    },
    "proximity_to_failure": {
        "dimension": "rpe_guard",
        "depends": ["proximity_to_failure", "recovery_state", "warning_load"],
        "pill": "RPE × Limitnähe",
    },
    "calendar_timing_logic": {
        "dimension": "calendar_timing",
        "depends": ["run_load", "recovery_state", "session_gap"],
        "pill": "Kalender × Timing",
    },
    "telegram_ops_discipline": {
        "dimension": "telegram_state",
        "depends": ["warning_load", "recovery_state", "session_gap"],
        "pill": "Telegram × Ops",
    },
    "inventory_prep_shopping": {
        "dimension": "inventory_flow",
        "depends": ["nutrition_adherence", "weight_trend", "recovery_state"],
        "pill": "Vorrat × Prep",
    },
    "explainability_governance": {
        "dimension": "explain_policy",
        "depends": ["warning_load", "strength_trend", "recovery_state"],
        "pill": "Explain × Regeln",
    },
    "macro_scaling_control": {
        "dimension": "portion_scaling",
        "depends": ["nutrition_adherence", "weight_trend", "run_load"],
        "pill": "Makros × Mengen",
    },
    "data_freshness_integrity": {
        "dimension": "data_integrity",
        "depends": ["strength_trend", "run_load", "nutrition_adherence"],
        "pill": "Daten × Frische",
    },
}


def _normalize_question(text: str) -> str:
    return re.sub(r"\s+", " ", str(text or "").strip().lower())


def _question_tokens(text: str) -> set[str]:
    stop = {
        "und", "oder", "der", "die", "das", "den", "dem", "des", "ein", "eine", "einer", "einem", "zu",
        "mit", "für", "von", "bei", "im", "in", "am", "an", "auf", "wenn", "soll", "core", "heute",
    }
    return {
        tok for tok in re.findall(r"[a-z0-9äöüß]+", _normalize_question(text))
        if len(tok) >= 3 and tok not in stop
    }


def _is_near_duplicate(question: str, seen_norms: set[str], seen_tokens: list[set[str]]) -> bool:
    q_norm = _normalize_question(question)
    if not q_norm:
        return True
    if q_norm in seen_norms:
        return True
    q_toks = _question_tokens(q_norm)
    if not q_toks:
        return True
    for other in seen_tokens:
        if not other:
            continue
        inter = len(q_toks & other)
        if inter == 0:
            continue
        sim = inter / max(1, len(q_toks | other))
        if sim >= 0.76:
            return True
    return False


def build_fixed_question_templates() -> list[dict[str, Any]]:
    merged_bank: dict[str, list[str]] = {topic: list(questions) for topic, questions in FIXED_QUESTION_BANK.items()}
    for topic, questions in ADDITIONAL_FIXED_QUESTION_BANK.items():
        merged_bank.setdefault(topic, []).extend(questions)
    merged_meta = dict(FIXED_QUESTION_META)
    merged_meta.update(ADDITIONAL_FIXED_QUESTION_META)

    templates: list[dict[str, Any]] = []
    seen_norms: set[str] = set()
    seen_tokens: list[set[str]] = []
    for topic, questions in merged_bank.items():
        meta = merged_meta.get(topic)
        if not isinstance(meta, dict):
            continue
        topic_seen = 0
        for idx, question in enumerate(questions, start=1):
            if _is_near_duplicate(question, seen_norms, seen_tokens):
                continue
            q_norm = _normalize_question(question)
            q_tokens = _question_tokens(question)
            seen_norms.add(q_norm)
            if q_tokens:
                seen_tokens.append(q_tokens)
            topic_seen += 1
            templates.append(
                {
                    "id": f"{topic}_bank_{idx:03d}_v2",
                    "topic": topic,
                    "kind": "principle",
                    "family": topic,
                    "dimension": meta["dimension"],
                    "pill": meta["pill"],
                    "base": question,
                    "depends": list(meta["depends"]),
                    "fixed_question": True,
                }
            )
        if topic_seen == 0 and questions:
            # Fallback: keep at least one question per topic if dedupe removed all.
            question = str(questions[0] or "").strip()
            if question:
                templates.append(
                    {
                        "id": f"{topic}_bank_fallback_v2",
                        "topic": topic,
                        "kind": "principle",
                        "family": topic,
                        "dimension": meta["dimension"],
                        "pill": meta["pill"],
                        "base": question,
                        "depends": list(meta["depends"]),
                        "fixed_question": True,
                    }
                )
    return templates
