#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3

[[ $EUID -eq 0 ]] || { echo "Run with: sudo $0" >&2; exit 1; }
CONFIG=/etc/liva/recovery/config.toml
mapfile -t DEVICE_CONFIG < <(python3 - "$CONFIG" <<'PY'
import sys
import tomllib

with open(sys.argv[1], "rb") as source:
    usb = tomllib.load(source)["usb"]
print(usb["uuid"])
print(usb["label"])
PY
)
UUID=${DEVICE_CONFIG[0]:-}
LABEL=${DEVICE_CONFIG[1]:-}
[[ -n "$UUID" && -n "$LABEL" ]] || { echo "Recovery USB config is incomplete" >&2; exit 1; }
DEVICE=$(blkid -U "$UUID" 2>/dev/null || true)
[[ -b "$DEVICE" ]] || { echo "Configured recovery USB is not present" >&2; exit 1; }
MOUNT=/mnt/liva-recovery
RECIPIENTS=/etc/liva/recovery/recipients.txt
IDENTITY_REL=backups/full-recovery/bootstrap/liva-recovery-identity.age
MOUNTED_HERE=0
TMP=""
cleanup() {
  [[ -n "${IDENTITY_TMP:-}" ]] && rm -f -- "$IDENTITY_TMP"
  [[ -n "$TMP" ]] && rm -rf -- "$TMP"
  [[ $MOUNTED_HERE -eq 1 ]] && umount "$MOUNT" || true
}
trap cleanup EXIT INT TERM

banner "LIVA Recovery-Key Bootstrap"

stage "Verify and mount the dedicated recovery USB"
say "This verifies only $DEVICE with UUID $UUID and label $LABEL."
[[ "$(blkid -s UUID -o value "$DEVICE")" == "$UUID" ]] || { warn "Unexpected UUID; stopping."; exit 1; }
[[ "$(lsblk -no LABEL "$DEVICE" | xargs)" == "$LABEL" ]] || { warn "Unexpected label; stopping."; exit 1; }
[[ "$(lsblk -no FSTYPE "$DEVICE" | xargs)" == "vfat" ]] || { warn "Unexpected filesystem; stopping."; exit 1; }
install -d -m 0700 "$MOUNT"
if ! findmnt -rn -S "$DEVICE" >/dev/null; then
  mount -o nodev,nosuid,noexec,uid=0,gid=0,umask=077 "$DEVICE" "$MOUNT"
  MOUNTED_HERE=1
fi
install -d -m 0700 "$MOUNT/$(dirname "$IDENTITY_REL")"

stage "Create and protect the recovery identity"
say "Enter the new master password once at the visible prompt. It remains only in the running process memory."
TMP=$(mktemp -d /dev/shm/liva-recovery-key.XXXXXX)
umask 077
age-keygen -o "$TMP/identity.txt" >/dev/null
age-keygen -y "$TMP/identity.txt" > "$TMP/recipient.txt"
IDENTITY_TMP="$MOUNT/$IDENTITY_REL.partial"
rm -f -- "$IDENTITY_TMP"
python3 - "$TMP/identity.txt" "$IDENTITY_TMP" "$TMP/identity-roundtrip.txt" <<'PY'
import getpass
import fcntl
import os
import pty
import select
import subprocess
import sys
import termios

identity, encrypted, roundtrip = sys.argv[1:]
password = getpass.getpass("Master password: ")

def run_age(command, prompts):
    master, slave = pty.openpty()
    def controlling_terminal():
        os.setsid()
        fcntl.ioctl(slave, termios.TIOCSCTTY, 0)
    process = subprocess.Popen(
        command,
        stdin=slave,
        stdout=slave,
        stderr=slave,
        close_fds=True,
        preexec_fn=controlling_terminal,
    )
    os.close(slave)
    pending = list(prompts)
    output = b""
    try:
        while process.poll() is None:
            readable, _, _ = select.select([master], [], [], 0.2)
            if not readable:
                continue
            try:
                data = os.read(master, 4096)
            except OSError:
                break
            if not data:
                break
            output += data
            lowered = output.lower()
            if pending and pending[0] in lowered:
                os.write(master, (password + "\n").encode())
                pending.pop(0)
        while True:
            try:
                data = os.read(master, 4096)
            except OSError:
                break
            if not data:
                break
            output += data
    finally:
        os.close(master)
    if process.wait() != 0 or pending:
        raise SystemExit("age passphrase operation failed")

run_age(["age", "-p", "-o", encrypted, identity], [b"enter passphrase", b"confirm passphrase"])
run_age(["age", "-d", "-o", roundtrip, encrypted], [b"enter passphrase"])
PY
age-keygen -y "$TMP/identity-roundtrip.txt" > "$TMP/recipient-roundtrip.txt"
cmp -- "$TMP/recipient.txt" "$TMP/recipient-roundtrip.txt"
install -d -m 0700 /etc/liva/recovery
install -m 0644 "$TMP/recipient.txt" "$RECIPIENTS"
mv -- "$IDENTITY_TMP" "$MOUNT/$IDENTITY_REL"
chmod 0600 "$MOUNT/$IDENTITY_REL"

stage "Synthetic encryption roundtrip"
printf 'liva-recovery-key-roundtrip\n' > "$TMP/payload.txt"
age -R "$RECIPIENTS" -o "$TMP/payload.age" "$TMP/payload.txt"
age -d -i "$TMP/identity-roundtrip.txt" "$TMP/payload.age" > "$TMP/payload-restored.txt"
cmp -- "$TMP/payload.txt" "$TMP/payload-restored.txt"
say "Recipient fingerprint (public): $(sha256sum "$RECIPIENTS" | awk '{print $1}')"
say "Encrypted identity written to: /$IDENTITY_REL"
say "Plaintext identity is being removed from RAM now."

finish
