from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date
from typing import Any


@dataclass(frozen=True)
class ScenarioExpected:
    final_kind: str
    mode: str
    reason_contains: str
    rpe_shift: float
    topset_delta_mainlifts: int
    user_one_liner_contains: str
    explain_primary: str
    explain_contributors_contains: list[str] = field(default_factory=list)
    explain_rules_triggered: list[str] = field(default_factory=list)
    explain_rules_not_triggered: list[str] = field(default_factory=list)
    chosen_session: str | None = None


@dataclass(frozen=True)
class Scenario:
    name: str
    day: date
    plan_ctx: dict[str, Any]
    signals_ctx: dict[str, Any]
    history_ctx: dict[str, Any]
    rules_ctx: dict[str, Any] = field(default_factory=dict)
    expected: ScenarioExpected = field(default_factory=lambda: ScenarioExpected(
        final_kind="train",
        mode="normal",
        reason_contains="PLAN_FIT",
        rpe_shift=0.0,
        topset_delta_mainlifts=0,
        user_one_liner_contains="Plan-Tag",
        explain_primary="PLAN_FIT",
    ))


DAY = date(2026, 2, 15)


SCENARIOS: list[Scenario] = [
    # PLAN DOMINANCE
    Scenario(
        name="s1_plan_rest_forces_rest",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "5/8", "days_to_deload": 3, "planned_session_kind": "rest"},
        signals_ctx={"rhr_state": "normal", "hrv_state": "up", "sick": False},
        history_ctx={},
        expected=ScenarioExpected(
            final_kind="rest",
            mode="recovery",
            reason_contains="PLAN_KIND",
            rpe_shift=0.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Plan-Ruhetag",
            explain_primary="PLAN_KIND",
            explain_rules_triggered=["PLAN_KIND"],
        ),
    ),
    Scenario(
        name="s2_plan_train_signals_ok_train",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "5/8", "days_to_deload": 3, "planned_session_kind": "train"},
        signals_ctx={"rhr_state": "normal", "hrv_state": "stable", "sick": False},
        history_ctx={},
        expected=ScenarioExpected(
            final_kind="train",
            mode="normal",
            reason_contains="PLAN_FIT",
            rpe_shift=0.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Voll nach Plan",
            explain_primary="PLAN_FIT",
            explain_rules_not_triggered=["PLAN_KIND", "SICKNESS_WINDOW"],
        ),
    ),
    # SICKNESS WINDOW
    Scenario(
        name="s3_sick_24h_not_extreme_light",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "3/8", "days_to_deload": 4, "planned_session_kind": "train", "planned_topset_mainlift": True},
        signals_ctx={"sick": True, "sick_hours_ago": 10, "rhr_state": "high", "hrv_state": "stable"},
        history_ctx={},
        expected=ScenarioExpected(
            final_kind="light",
            mode="recovery",
            reason_contains="SICKNESS_WINDOW",
            rpe_shift=-1.0,
            topset_delta_mainlifts=-1,
            user_one_liner_contains="Heute leichter",
            explain_primary="SICKNESS_WINDOW",
            explain_contributors_contains=["FATIGUE_STATE"],
            explain_rules_triggered=["SICKNESS_WINDOW", "FATIGUE_STATE"],
        ),
    ),
    Scenario(
        name="s4_sick_24h_extreme_rest",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "3/8", "days_to_deload": 4, "planned_session_kind": "train"},
        signals_ctx={"sick": True, "sick_hours_ago": 4, "rhr_state": "extreme", "hrv_state": "down"},
        history_ctx={},
        expected=ScenarioExpected(
            final_kind="rest",
            mode="recovery",
            reason_contains="SICKNESS_SEVERITY",
            rpe_shift=0.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="pausieren",
            explain_primary="SICKNESS_SEVERITY",
            explain_contributors_contains=["SICKNESS_WINDOW"],
            explain_rules_triggered=["SICKNESS_WINDOW", "SICKNESS_SEVERITY"],
        ),
    ),
    Scenario(
        name="s5_sick_older_24h_ignored",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "3/8", "days_to_deload": 4, "planned_session_kind": "train"},
        signals_ctx={"sick": True, "sick_hours_ago": 30, "rhr_state": "normal", "hrv_state": "stable"},
        history_ctx={},
        expected=ScenarioExpected(
            final_kind="train",
            mode="normal",
            reason_contains="PLAN_FIT",
            rpe_shift=0.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Voll nach Plan",
            explain_primary="PLAN_FIT",
            explain_rules_not_triggered=["SICKNESS_WINDOW", "SICKNESS_SEVERITY"],
        ),
    ),
    # PERIODIZATION
    Scenario(
        name="s6_overreach_expected_fatigue_train",
        day=DAY,
        plan_ctx={"phase": "OVERREACH", "week": "7/8", "days_to_deload": 2, "planned_session_kind": "train"},
        signals_ctx={"sick": False, "rhr_state": "high", "hrv_state": "down"},
        history_ctx={},
        expected=ScenarioExpected(
            final_kind="train",
            mode="overreach",
            reason_contains="PLAN_FIT",
            rpe_shift=0.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Overreach-Phase",
            explain_primary="PLAN_FIT",
            explain_contributors_contains=["FATIGUE_STATE"],
            explain_rules_triggered=["PLAN_FIT", "FATIGUE_STATE"],
        ),
    ),
    Scenario(
        name="s7_overreach_extreme_beyond_expected_light",
        day=DAY,
        plan_ctx={"phase": "OVERREACH", "week": "7/8", "days_to_deload": 2, "planned_session_kind": "train"},
        signals_ctx={"sick": False, "rhr_state": "extreme", "hrv_state": "down"},
        history_ctx={},
        expected=ScenarioExpected(
            final_kind="light",
            mode="overreach",
            reason_contains="FATIGUE_STATE",
            rpe_shift=-1.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Heute leichter",
            explain_primary="FATIGUE_STATE",
            explain_contributors_contains=[],
            explain_rules_triggered=["FATIGUE_STATE"],
        ),
    ),
    Scenario(
        name="s8_last_before_deload_push_allowed",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "7/8", "days_to_deload": 1, "planned_session_kind": "train"},
        signals_ctx={"sick": False, "rhr_state": "high", "hrv_state": "down"},
        history_ctx={},
        expected=ScenarioExpected(
            final_kind="train",
            mode="overreach",
            reason_contains="PLAN_FIT",
            rpe_shift=0.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Overreach-Phase",
            explain_primary="PLAN_FIT",
            explain_contributors_contains=["DELOAD_TIMING", "FATIGUE_STATE"],
            explain_rules_triggered=["DELOAD_TIMING", "PLAN_FIT", "FATIGUE_STATE"],
        ),
    ),
    Scenario(
        name="s9_deload_week_train_deload_mode",
        day=DAY,
        plan_ctx={"phase": "DELOAD", "week": "8/8", "days_to_deload": 0, "planned_session_kind": "train", "planned_topset_mainlift": True},
        signals_ctx={"sick": False, "rhr_state": "normal", "hrv_state": "stable"},
        history_ctx={},
        expected=ScenarioExpected(
            final_kind="train",
            mode="deload",
            reason_contains="DELOAD_TIMING",
            rpe_shift=-1.0,
            topset_delta_mainlifts=-1,
            user_one_liner_contains="Deload",
            explain_primary="PLAN_FIT",
            explain_contributors_contains=["DELOAD_TIMING"],
            explain_rules_triggered=["DELOAD_TIMING"],
        ),
    ),
    # MISMATCH HANDLING
    Scenario(
        name="s10_build_high_pulse_and_down_light",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "4/8", "days_to_deload": 5, "planned_session_kind": "train"},
        signals_ctx={"sick": False, "rhr_state": "high", "hrv_state": "down"},
        history_ctx={},
        expected=ScenarioExpected(
            final_kind="light",
            mode="recovery",
            reason_contains="FATIGUE_STATE",
            rpe_shift=-1.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Heute leichter",
            explain_primary="FATIGUE_STATE",
            explain_contributors_contains=[],
            explain_rules_triggered=["FATIGUE_STATE"],
        ),
    ),
    Scenario(
        name="s11_build_only_hrv_down_train",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "4/8", "days_to_deload": 5, "planned_session_kind": "train"},
        signals_ctx={"sick": False, "rhr_state": "normal", "hrv_state": "down"},
        history_ctx={},
        expected=ScenarioExpected(
            final_kind="train",
            mode="normal",
            reason_contains="PLAN_FIT",
            rpe_shift=0.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Voll nach Plan",
            explain_primary="PLAN_FIT",
            explain_rules_not_triggered=["FATIGUE_STATE"],
        ),
    ),
    Scenario(
        name="s12_build_only_pulse_high_light",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "4/8", "days_to_deload": 5, "planned_session_kind": "train", "expected_fatigue_level": "low"},
        signals_ctx={"sick": False, "rhr_state": "high", "hrv_state": "stable"},
        history_ctx={},
        expected=ScenarioExpected(
            final_kind="light",
            mode="recovery",
            reason_contains="FATIGUE_STATE",
            rpe_shift=-1.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Heute leichter",
            explain_primary="FATIGUE_STATE",
            explain_rules_triggered=["FATIGUE_STATE"],
        ),
    ),
    # REST LAST RESORT
    Scenario(
        name="s13_extreme_not_expected_rest",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "4/8", "days_to_deload": 5, "planned_session_kind": "train"},
        signals_ctx={"sick": False, "rhr_state": "extreme", "hrv_state": "down"},
        history_ctx={},
        expected=ScenarioExpected(
            final_kind="light",
            mode="recovery",
            reason_contains="FATIGUE_STATE",
            rpe_shift=-1.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Heute leichter",
            explain_primary="FATIGUE_STATE",
            explain_contributors_contains=[],
            explain_rules_triggered=["FATIGUE_STATE"],
        ),
    ),
    Scenario(
        name="s14_non_extreme_never_rest_light",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "4/8", "days_to_deload": 5, "planned_session_kind": "train", "expected_fatigue_level": "low"},
        signals_ctx={"sick": False, "rhr_state": "high", "hrv_state": "stable"},
        history_ctx={"last_sessions": [{"ts": "2026-02-15T00:30:00", "kind": "train", "intensity": "hard"}]},
        expected=ScenarioExpected(
            final_kind="light",
            mode="recovery",
            reason_contains="FATIGUE_STATE",
            rpe_shift=-1.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Heute leichter",
            explain_primary="FATIGUE_STATE",
            explain_contributors_contains=["RECENCY"],
            explain_rules_triggered=["FATIGUE_STATE", "RECENCY"],
        ),
    ),
    # SUBJECTIVE
    Scenario(
        name="s15_subjective_low_motivation_ignored",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "2/8", "days_to_deload": 6, "planned_session_kind": "train"},
        signals_ctx={"sick": False, "rhr_state": "normal", "hrv_state": "stable", "subjective_low_motivation": True},
        history_ctx={},
        expected=ScenarioExpected(
            final_kind="train",
            mode="normal",
            reason_contains="PLAN_FIT",
            rpe_shift=0.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Voll nach Plan",
            explain_primary="PLAN_FIT",
            explain_contributors_contains=["SUBJECTIVE_IGNORED"],
            explain_rules_triggered=["SUBJECTIVE_IGNORED"],
        ),
    ),
    # SCHEDULING + GYM PRIORITY
    Scenario(
        name="s16_run_planned_but_gym_pending_choose_gym",
        day=DAY,
        plan_ctx={
            "phase": "BUILD",
            "week": "3/8",
            "days_to_deload": 4,
            "planned_session_kind": "run",
            "pending_gym_in_week": True,
            "pending_gym_session_name": "Upper A",
        },
        signals_ctx={"sick": False, "rhr_state": "normal", "hrv_state": "stable"},
        history_ctx={},
        expected=ScenarioExpected(
            final_kind="train",
            mode="normal",
            reason_contains="GYM_PRIORITY",
            rpe_shift=0.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Voll nach Plan",
            explain_primary="PLAN_FIT",
            explain_contributors_contains=["GYM_PRIORITY"],
            explain_rules_triggered=["GYM_PRIORITY"],
            chosen_session="Upper A",
        ),
    ),
    Scenario(
        name="s17_reorder_only_no_penalty",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "3/8", "days_to_deload": 4, "planned_session_kind": "train"},
        signals_ctx={"sick": False, "rhr_state": "normal", "hrv_state": "stable"},
        history_ctx={"session_reorder_only": True},
        expected=ScenarioExpected(
            final_kind="train",
            mode="normal",
            reason_contains="PLAN_FIT",
            rpe_shift=0.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Voll nach Plan",
            explain_primary="PLAN_FIT",
            explain_contributors_contains=["SESSION_REORDER_ONLY"],
            explain_rules_triggered=["SESSION_REORDER_ONLY"],
        ),
    ),
    Scenario(
        name="s18_missed_gym_rescheduled_inside_week",
        day=DAY,
        plan_ctx={
            "phase": "BUILD",
            "week": "3/8",
            "days_to_deload": 4,
            "planned_session_kind": "run",
            "pending_gym_in_week": True,
            "pending_gym_session_name": "Lower B",
        },
        signals_ctx={"sick": False, "rhr_state": "normal", "hrv_state": "stable"},
        history_ctx={"missed_gym_earlier": True},
        expected=ScenarioExpected(
            final_kind="train",
            mode="normal",
            reason_contains="GYM_PRIORITY",
            rpe_shift=0.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Voll nach Plan",
            explain_primary="PLAN_FIT",
            explain_contributors_contains=["GYM_PRIORITY"],
            explain_rules_triggered=["GYM_PRIORITY"],
            chosen_session="Lower B",
        ),
    ),
    # MISSING/LATE LOGGING
    Scenario(
        name="s19_last_session_missing_no_penalty",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "2/8", "days_to_deload": 6, "planned_session_kind": "train"},
        signals_ctx={"sick": False, "rhr_state": "normal", "hrv_state": "stable"},
        history_ctx={"last_session_missing": True},
        expected=ScenarioExpected(
            final_kind="train",
            mode="normal",
            reason_contains="PLAN_FIT",
            rpe_shift=0.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Voll nach Plan",
            explain_primary="PLAN_FIT",
            explain_contributors_contains=["LATE_LOGGING"],
            explain_rules_triggered=["LATE_LOGGING"],
        ),
    ),
    # BOUNDARIES
    Scenario(
        name="s21_pulse_high_boundary_exact",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "4/8", "days_to_deload": 5, "planned_session_kind": "train", "expected_fatigue_level": "low"},
        signals_ctx={"sick": False, "hrv_state": "stable", "rhr_delta": 4.0},
        history_ctx={},
        rules_ctx={"rhr_high_delta_threshold": 4.0, "rhr_extreme_delta_threshold": 8.0},
        expected=ScenarioExpected(
            final_kind="light",
            mode="recovery",
            reason_contains="FATIGUE_STATE",
            rpe_shift=-1.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Heute leichter",
            explain_primary="FATIGUE_STATE",
            explain_rules_triggered=["FATIGUE_STATE"],
        ),
    ),
    Scenario(
        name="s22_pulse_extreme_boundary_exact",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "4/8", "days_to_deload": 5, "planned_session_kind": "train"},
        signals_ctx={"sick": False, "hrv_state": "down", "rhr_delta": 8.0},
        history_ctx={},
        rules_ctx={"rhr_high_delta_threshold": 4.0, "rhr_extreme_delta_threshold": 8.0},
        expected=ScenarioExpected(
            final_kind="light",
            mode="recovery",
            reason_contains="FATIGUE_STATE",
            rpe_shift=-1.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Heute leichter",
            explain_primary="FATIGUE_STATE",
            explain_rules_triggered=["FATIGUE_STATE"],
        ),
    ),
    Scenario(
        name="s23_hrv_down_boundary_exact",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "4/8", "days_to_deload": 5, "planned_session_kind": "train"},
        signals_ctx={"sick": False, "rhr_state": "normal", "hrv_ratio": 0.90},
        history_ctx={},
        rules_ctx={"hrv_down_ratio_threshold": 0.90},
        expected=ScenarioExpected(
            final_kind="train",
            mode="normal",
            reason_contains="PLAN_FIT",
            rpe_shift=0.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Voll nach Plan",
            explain_primary="PLAN_FIT",
            explain_rules_not_triggered=["FATIGUE_STATE"],
        ),
    ),
    Scenario(
        name="s24_days_to_deload_1_push_allowed_train",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "7/8", "days_to_deload": 1, "planned_session_kind": "train"},
        signals_ctx={"sick": False, "rhr_state": "high", "hrv_state": "down"},
        history_ctx={},
        expected=ScenarioExpected(
            final_kind="train",
            mode="overreach",
            reason_contains="PLAN_FIT",
            rpe_shift=0.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Overreach-Phase",
            explain_primary="PLAN_FIT",
            explain_contributors_contains=["DELOAD_TIMING", "FATIGUE_STATE"],
            explain_rules_triggered=["DELOAD_TIMING", "PLAN_FIT", "FATIGUE_STATE"],
        ),
    ),
    Scenario(
        name="s25_days_to_deload_2_same_signals_light",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "6/8", "days_to_deload": 2, "planned_session_kind": "train"},
        signals_ctx={"sick": False, "rhr_state": "high", "hrv_state": "down"},
        history_ctx={},
        expected=ScenarioExpected(
            final_kind="train",
            mode="overreach",
            reason_contains="PLAN_FIT",
            rpe_shift=0.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Overreach-Phase",
            explain_primary="PLAN_FIT",
            explain_contributors_contains=["FATIGUE_STATE"],
            explain_rules_triggered=["PLAN_FIT", "FATIGUE_STATE"],
        ),
    ),
    # CARDIO RE-INTRO (Z2 statt Rest/Off)
    Scenario(
        name="s26_cardio_debt_plan_rest_default_stays_rest",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "4/8", "days_to_deload": 4, "planned_session_kind": "rest"},
        signals_ctx={"sick": False, "rhr_state": "normal", "hrv_state": "stable"},
        history_ctx={"planned_runs_last_3_weeks": 6, "performed_runs_last_3_weeks": 1, "days_since_last_run": 10},
        rules_ctx={"allow_z2_on_plan_rest": False},
        expected=ScenarioExpected(
            final_kind="rest",
            mode="recovery",
            reason_contains="PLAN_KIND",
            rpe_shift=0.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Plan-Ruhetag",
            explain_primary="PLAN_KIND",
            explain_rules_triggered=["CARDIO_DEBT"],
        ),
    ),
    Scenario(
        name="s27_cardio_debt_plan_rest_allowed_reintro",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "4/8", "days_to_deload": 4, "planned_session_kind": "rest"},
        signals_ctx={"sick": False, "rhr_state": "normal", "hrv_state": "stable"},
        history_ctx={"planned_runs_last_3_weeks": 6, "performed_runs_last_3_weeks": 1, "days_since_last_run": 10},
        rules_ctx={"allow_z2_on_plan_rest": True, "cardio_reintro_duration_min": 30},
        expected=ScenarioExpected(
            final_kind="light",
            mode="recovery",
            reason_contains="CARDIO_REINTRO",
            rpe_shift=0.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Reintro: Z2 statt Pause",
            explain_primary="CARDIO_REINTRO",
            explain_contributors_contains=["CARDIO_DEBT", "RECOVERY_GOOD", "NO_GYM_CONFLICT"],
            explain_rules_triggered=["CARDIO_DEBT", "RECOVERY_GOOD", "NO_GYM_CONFLICT", "PLAN_REST_Z2_ALLOWED", "CARDIO_REINTRO"],
            chosen_session="Z2 Run",
        ),
    ),
    Scenario(
        name="s28_cardio_debt_plan_off_allowed_reintro",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "4/8", "days_to_deload": 4, "planned_session_kind": "off"},
        signals_ctx={"sick": False, "rhr_state": "normal", "hrv_state": "up"},
        history_ctx={"planned_runs_last_3_weeks": 4, "performed_runs_last_3_weeks": 0, "days_since_last_run": 14},
        rules_ctx={"allow_z2_on_plan_rest": True, "cardio_reintro_duration_min": 35},
        expected=ScenarioExpected(
            final_kind="light",
            mode="recovery",
            reason_contains="CARDIO_REINTRO",
            rpe_shift=0.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Reintro: Z2 statt Pause",
            explain_primary="CARDIO_REINTRO",
            explain_contributors_contains=["CARDIO_DEBT", "RECOVERY_GOOD"],
            explain_rules_triggered=["CARDIO_DEBT", "RECOVERY_GOOD", "NO_GYM_CONFLICT", "PLAN_REST_Z2_ALLOWED", "CARDIO_REINTRO"],
            chosen_session="Z2 Run",
        ),
    ),
    Scenario(
        name="s29_cardio_debt_but_high_pulse_no_reintro",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "4/8", "days_to_deload": 4, "planned_session_kind": "rest"},
        signals_ctx={"sick": False, "rhr_state": "high", "hrv_state": "stable"},
        history_ctx={"planned_runs_last_3_weeks": 6, "performed_runs_last_3_weeks": 0, "days_since_last_run": 12},
        rules_ctx={"allow_z2_on_plan_rest": True},
        expected=ScenarioExpected(
            final_kind="rest",
            mode="recovery",
            reason_contains="PLAN_KIND",
            rpe_shift=0.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Plan-Ruhetag",
            explain_primary="PLAN_KIND",
            explain_rules_triggered=["CARDIO_DEBT"],
            explain_rules_not_triggered=["RECOVERY_GOOD", "CARDIO_REINTRO"],
        ),
    ),
    Scenario(
        name="s30_cardio_debt_but_hrv_down_no_reintro",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "4/8", "days_to_deload": 4, "planned_session_kind": "rest"},
        signals_ctx={"sick": False, "rhr_state": "normal", "hrv_state": "down"},
        history_ctx={"planned_runs_last_3_weeks": 5, "performed_runs_last_3_weeks": 1, "days_since_last_run": 9},
        rules_ctx={"allow_z2_on_plan_rest": True},
        expected=ScenarioExpected(
            final_kind="rest",
            mode="recovery",
            reason_contains="PLAN_KIND",
            rpe_shift=0.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Plan-Ruhetag",
            explain_primary="PLAN_KIND",
            explain_rules_triggered=[],
            explain_rules_not_triggered=["RECOVERY_GOOD", "CARDIO_REINTRO"],
        ),
    ),
    Scenario(
        name="s31_cardio_debt_but_sick_active_no_reintro",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "4/8", "days_to_deload": 4, "planned_session_kind": "rest"},
        signals_ctx={"sick": True, "sick_hours_ago": 6, "rhr_state": "normal", "hrv_state": "stable"},
        history_ctx={"planned_runs_last_3_weeks": 5, "performed_runs_last_3_weeks": 1, "days_since_last_run": 11},
        rules_ctx={"allow_z2_on_plan_rest": True},
        expected=ScenarioExpected(
            final_kind="rest",
            mode="recovery",
            reason_contains="PLAN_KIND",
            rpe_shift=0.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Plan-Ruhetag",
            explain_primary="PLAN_KIND",
            explain_rules_triggered=["CARDIO_DEBT", "SICKNESS_WINDOW"],
            explain_rules_not_triggered=["RECOVERY_GOOD", "CARDIO_REINTRO"],
        ),
    ),
    Scenario(
        name="s32_cardio_debt_but_gym_conflict_no_reintro",
        day=DAY,
        plan_ctx={
            "phase": "BUILD",
            "week": "4/8",
            "days_to_deload": 4,
            "planned_session_kind": "rest",
            "today_gym_planned": True,
            "should_use_slot_for_gym_today": True,
        },
        signals_ctx={"sick": False, "rhr_state": "normal", "hrv_state": "stable"},
        history_ctx={"planned_runs_last_3_weeks": 5, "performed_runs_last_3_weeks": 0, "days_since_last_run": 12},
        rules_ctx={"allow_z2_on_plan_rest": True},
        expected=ScenarioExpected(
            final_kind="rest",
            mode="recovery",
            reason_contains="PLAN_KIND",
            rpe_shift=0.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Plan-Ruhetag",
            explain_primary="PLAN_KIND",
            explain_rules_triggered=["CARDIO_DEBT", "RECOVERY_GOOD"],
            explain_rules_not_triggered=["NO_GYM_CONFLICT", "CARDIO_REINTRO"],
        ),
    ),
    Scenario(
        name="s33_no_cardio_debt_no_reintro",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "4/8", "days_to_deload": 4, "planned_session_kind": "rest"},
        signals_ctx={"sick": False, "rhr_state": "normal", "hrv_state": "stable"},
        history_ctx={"planned_runs_last_3_weeks": 3, "performed_runs_last_3_weeks": 3, "days_since_last_run": 2},
        rules_ctx={"allow_z2_on_plan_rest": True},
        expected=ScenarioExpected(
            final_kind="rest",
            mode="recovery",
            reason_contains="PLAN_KIND",
            rpe_shift=0.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Plan-Ruhetag",
            explain_primary="PLAN_KIND",
            explain_rules_not_triggered=["CARDIO_DEBT", "CARDIO_REINTRO"],
        ),
    ),
    Scenario(
        name="s34_cardio_debt_days_since_boundary_7",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "4/8", "days_to_deload": 4, "planned_session_kind": "off"},
        signals_ctx={"sick": False, "rhr_state": "normal", "hrv_state": "stable"},
        history_ctx={"planned_runs_last_3_weeks": 3, "performed_runs_last_3_weeks": 1, "days_since_last_run": 7},
        rules_ctx={"allow_z2_on_plan_rest": True, "cardio_debt_min_days_since_last_run": 7},
        expected=ScenarioExpected(
            final_kind="off",
            mode="recovery",
            reason_contains="PLAN_KIND",
            rpe_shift=0.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Plan-Off-Tag",
            explain_primary="PLAN_KIND",
            explain_rules_not_triggered=["CARDIO_DEBT", "CARDIO_REINTRO"],
        ),
    ),
    # PLAN_FIT gates FATIGUE_STATE (targeted regression cases)
    Scenario(
        name="t1_expected_high_observed_moderate_train",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "7/8", "days_to_deload": 1, "planned_session_kind": "train"},
        signals_ctx={"sick": False, "rhr_state": "high", "hrv_state": "stable"},
        history_ctx={},
        expected=ScenarioExpected(
            final_kind="train",
            mode="overreach",
            reason_contains="PLAN_FIT",
            rpe_shift=0.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Overreach-Phase",
            explain_primary="PLAN_FIT",
            explain_contributors_contains=["DELOAD_TIMING", "FATIGUE_STATE"],
            explain_rules_triggered=["DELOAD_TIMING", "PLAN_FIT", "FATIGUE_STATE"],
        ),
    ),
    Scenario(
        name="t2_expected_high_observed_extreme_safety_light",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "7/8", "days_to_deload": 1, "planned_session_kind": "train"},
        signals_ctx={"sick": False, "rhr_state": "extreme", "hrv_state": "down"},
        history_ctx={},
        expected=ScenarioExpected(
            final_kind="light",
            mode="overreach",
            reason_contains="FATIGUE_STATE",
            rpe_shift=-1.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Heute leichter",
            explain_primary="FATIGUE_STATE",
            explain_rules_triggered=["FATIGUE_STATE", "DELOAD_TIMING"],
        ),
    ),
    Scenario(
        name="t3_expected_low_observed_moderate_light",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "2/8", "days_to_deload": 5, "planned_session_kind": "train", "expected_fatigue_level": "low"},
        signals_ctx={"sick": False, "rhr_state": "high", "hrv_state": "stable"},
        history_ctx={},
        expected=ScenarioExpected(
            final_kind="light",
            mode="recovery",
            reason_contains="FATIGUE_STATE",
            rpe_shift=-1.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Heute leichter",
            explain_primary="FATIGUE_STATE",
            explain_rules_triggered=["FATIGUE_STATE"],
        ),
    ),
    Scenario(
        name="t4_expected_high_observed_high_train",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "7/8", "days_to_deload": 1, "planned_session_kind": "train"},
        signals_ctx={"sick": False, "rhr_state": "high", "hrv_state": "down"},
        history_ctx={},
        expected=ScenarioExpected(
            final_kind="train",
            mode="overreach",
            reason_contains="PLAN_FIT",
            rpe_shift=0.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Overreach-Phase",
            explain_primary="PLAN_FIT",
            explain_contributors_contains=["DELOAD_TIMING", "FATIGUE_STATE"],
            explain_rules_triggered=["DELOAD_TIMING", "PLAN_FIT", "FATIGUE_STATE"],
        ),
    ),
    Scenario(
        name="t5_planfit_moderate_note_only_stays_train",
        day=DAY,
        plan_ctx={
            "phase": "BUILD",
            "week": "4/8",
            "days_to_deload": 4,
            "planned_session_kind": "train",
            "expected_fatigue_level": "moderate",
        },
        signals_ctx={"sick": False, "rhr_state": "high", "hrv_state": "stable"},
        history_ctx={},
        expected=ScenarioExpected(
            final_kind="train",
            mode="normal",
            reason_contains="PLAN_FIT",
            rpe_shift=0.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Voll nach Plan",
            explain_primary="PLAN_FIT",
            explain_contributors_contains=["FATIGUE_STATE"],
            explain_rules_triggered=["PLAN_FIT", "FATIGUE_STATE"],
        ),
    ),
    Scenario(
        name="t6_real_like_late_build_moderate_train",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "7/8", "days_to_deload": 2, "planned_session_kind": "train"},
        signals_ctx={"sick": False, "rhr_state": "high", "hrv_state": "stable"},
        history_ctx={},
        expected=ScenarioExpected(
            final_kind="train",
            mode="overreach",
            reason_contains="PLAN_FIT",
            rpe_shift=0.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Overreach-Phase",
            explain_primary="PLAN_FIT",
            explain_contributors_contains=["FATIGUE_STATE"],
            explain_rules_triggered=["PLAN_FIT", "FATIGUE_STATE"],
        ),
    ),
    # Additional named scenarios for expected-fatigue and cardio/missing-log fixes
    Scenario(
        name="p1_week7of8_expected_high_mode_overreach",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "7/8", "days_to_deload": None, "planned_session_kind": "train"},
        signals_ctx={"sick": False, "rhr_state": "high", "hrv_state": "stable"},
        history_ctx={},
        expected=ScenarioExpected(
            final_kind="train",
            mode="overreach",
            reason_contains="PLAN_FIT",
            rpe_shift=0.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Overreach-Phase",
            explain_primary="PLAN_FIT",
            explain_contributors_contains=["FATIGUE_STATE"],
            explain_rules_triggered=["PLAN_FIT", "FATIGUE_STATE"],
        ),
    ),
    Scenario(
        name="p2_days_to_deload_2_expected_high",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "6/8", "days_to_deload": 2, "planned_session_kind": "train"},
        signals_ctx={"sick": False, "rhr_state": "high", "hrv_state": "stable"},
        history_ctx={},
        expected=ScenarioExpected(
            final_kind="train",
            mode="overreach",
            reason_contains="PLAN_FIT",
            rpe_shift=0.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Overreach-Phase",
            explain_primary="PLAN_FIT",
            explain_contributors_contains=["FATIGUE_STATE"],
            explain_rules_triggered=["PLAN_FIT", "FATIGUE_STATE"],
        ),
    ),
    Scenario(
        name="c1_cardio_debt_reintro_on_plan_rest",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "4/8", "days_to_deload": 4, "planned_session_kind": "rest"},
        signals_ctx={"sick": False, "rhr_state": "normal", "hrv_state": "stable"},
        history_ctx={"planned_runs_last_3_weeks": 6, "performed_runs_last_3_weeks": 1, "days_since_last_run": 10},
        rules_ctx={"allow_z2_on_plan_rest": True},
        expected=ScenarioExpected(
            final_kind="light",
            mode="recovery",
            reason_contains="CARDIO_REINTRO",
            rpe_shift=0.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Reintro: Z2 statt Pause",
            explain_primary="CARDIO_REINTRO",
            explain_contributors_contains=["CARDIO_DEBT", "RECOVERY_GOOD", "NO_GYM_CONFLICT"],
            explain_rules_triggered=["CARDIO_DEBT", "RECOVERY_GOOD", "NO_GYM_CONFLICT", "PLAN_REST_Z2_ALLOWED", "CARDIO_REINTRO"],
            chosen_session="Z2 Run",
        ),
    ),
    Scenario(
        name="c2_cardio_debt_blocked_by_bad_recovery",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "4/8", "days_to_deload": 4, "planned_session_kind": "rest"},
        signals_ctx={"sick": False, "rhr_state": "high", "hrv_state": "down"},
        history_ctx={"planned_runs_last_3_weeks": 6, "performed_runs_last_3_weeks": 0, "days_since_last_run": 12},
        rules_ctx={"allow_z2_on_plan_rest": True},
        expected=ScenarioExpected(
            final_kind="rest",
            mode="recovery",
            reason_contains="PLAN_KIND",
            rpe_shift=0.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Plan-Ruhetag",
            explain_primary="PLAN_KIND",
            explain_rules_triggered=["CARDIO_DEBT"],
            explain_rules_not_triggered=["RECOVERY_GOOD", "CARDIO_REINTRO"],
        ),
    ),
    Scenario(
        name="c3_cardio_debt_never_displaces_gym",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "4/8", "days_to_deload": 4, "planned_session_kind": "train"},
        signals_ctx={"sick": False, "rhr_state": "normal", "hrv_state": "stable"},
        history_ctx={"planned_runs_last_3_weeks": 6, "performed_runs_last_3_weeks": 0, "days_since_last_run": 15},
        rules_ctx={"allow_z2_on_plan_rest": True},
        expected=ScenarioExpected(
            final_kind="train",
            mode="normal",
            reason_contains="PLAN_FIT",
            rpe_shift=0.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Voll nach Plan",
            explain_primary="PLAN_FIT",
            explain_rules_not_triggered=["CARDIO_REINTRO"],
        ),
    ),
    Scenario(
        name="h1_missing_gym_log_assume_completed",
        day=DAY,
        plan_ctx={"phase": "BUILD", "week": "4/8", "days_to_deload": 5, "planned_session_kind": "train"},
        signals_ctx={"sick": False, "rhr_state": "normal", "hrv_state": "stable"},
        history_ctx={"assume_completed_if_missing": True, "planned_recent_sessions": [{"hours_ago": 20, "kind": "train"}]},
        expected=ScenarioExpected(
            final_kind="train",
            mode="normal",
            reason_contains="PLAN_FIT",
            rpe_shift=0.0,
            topset_delta_mainlifts=0,
            user_one_liner_contains="Voll nach Plan",
            explain_primary="PLAN_FIT",
            explain_rules_not_triggered=["RECENCY"],
        ),
    ),
]
